Repository openshift/openshift-origin-design, pull requests merged in 2018-09, with the labels that each got.

#100 Adding guidelines for empty states in the converged console
  README.md
  web-console/4.0-designs/empty-states/empty-states.md
  web-console/4.0-designs/empty-states/img/ES_access.png
  web-console/4.0-designs/empty-states/img/ES_create.png
  web-console/4.0-designs/empty-states/img/ES_feature.png
  web-console/4.0-designs/empty-states/img/ES_filter.png
  web-console/4.0-designs/empty-states/img/ES_overview.png
Labels: retest-not-required-docs-only, size/M

#104 Adding guidelines for Breadcrumbs in the converged console
  README.md
  web-console/4.0-designs/breadcrumbs/breadcrumbs.md
  web-console/4.0-designs/breadcrumbs/img/breadcrumbs.png
  web-console/4.0-designs/breadcrumbs/img/no-parent.png
  web-console/4.0-designs/breadcrumbs/img/responsive.png
  web-console/4.0-designs/breadcrumbs/img/summary.png
  web-console/4.0-designs/breadcrumbs/img/three-leaves.png
  web-console/4.0-designs/breadcrumbs/img/two-leaves.png
Labels: size/M

#101 Adding Environment Design
  README.md
  web-console/4.0-designs/environment/environment.md
  web-console/4.0-designs/environment/img/EV-1.png
  web-console/4.0-designs/environment/img/EV-2-readonly-2.png
  web-console/4.0-designs/environment/img/EV-2.png
  web-console/4.0-designs/environment/img/EV-2B.png
  web-console/4.0-designs/environment/img/EV-3.png
  web-console/4.0-designs/environment/img/EV-4.png
Labels: size/M

#105 Updating file name (fixing broken link)
  web-console/4.0-designs/code-editors/code-editors.md
Labels: size/XS

#106 Fixing Code Editors link in README
  README.md
Labels: size/XS

#114 Updating quick start guide following documentation of help menu
  web-console/4.0-designs/quick-start-guide/img/HelpMenu.png
  web-console/4.0-designs/quick-start-guide/img/horizontal.png
  web-console/4.0-designs/quick-start-guide/img/quick-start-guide.png
  web-console/4.0-designs/quick-start-guide/img/vertical.png
  web-console/4.0-designs/quick-start-guide/quick-start-guide.md
Labels: size/M

#108 Adding guidelines for create from YAML in the converged console
  README.md
  web-console/4.0-designs/create-from-YAML/create-from-YAML.md
  web-console/4.0-designs/create-from-YAML/img/YAML-Button.png
  web-console/4.0-designs/create-from-YAML/img/YAML-Create.png
  web-console/4.0-designs/create-from-YAML/img/YAML-Error.png
  web-console/4.0-designs/create-from-YAML/img/YAML-Success.png
  web-console/4.0-designs/create-from-YAML/img/YAML-Template.png
Labels: size/M

#117 Creating "Future" section in the documentation for forward-looking designs
  README.md
  web-console/4.0-designs/actions/actions.md
  web-console/futures/actions2/actions2.md
  web-console/futures/actions2/img/3.png
  web-console/futures/actions2/img/4.png
  web-console/futures/actions2/img/5.png
  web-console/futures/breadcrumbs/breadcrumbs.md
  web-console/futures/breadcrumbs/img/breadcrumbs.png
  web-console/futures/breadcrumbs/img/no-parent.png
  web-console/futures/breadcrumbs/img/responsive.png
  web-console/futures/breadcrumbs/img/summary.png
  web-console/futures/breadcrumbs/img/three-leaves.png
  web-console/futures/breadcrumbs/img/two-leaves.png
Labels: size/M
