Repository openshift/openshift-origin-design, pull requests merged in 2018-03, with the labels that each got.

#75 Storage capacity consumed
  web-console/project-details/img/storage-details-mobile.png
  web-console/project-details/img/storage-details.png
  web-console/project-details/img/storage-list.png
  web-console/project-details/img/storage-metrics-on-add-storage.png
  web-console/project-details/img/storage-metrics-on-deployment-details.png
  web-console/project-details/storage-metrics.md
Labels: size/M

#78 Adds Conceptual Design section with two pages under it: CNV and mobile
  README.md
  web-console/conceptual-designs/cnv.md
  web-console/conceptual-designs/mobile.md
Labels: size/S

#79 Adding catalog concepts and cleaning up
  web-console/conceptual-designs/catalog.md
  web-console/conceptual-designs/cnv.md
  web-console/conceptual-designs/mobile.md
Labels: size/S

#80 Weighted search
  web-console/homepage/search-filter.md
Labels: size/XS
