Repository openshift/openshift-origin-design, pull requests merged in 2018-12, with the labels that each got.

#132 [WIP] Adding dashboard view with quotas to Overview documentation
  README.md
  web-console/4.0-designs/dashboard/dashboard.md
  web-console/4.0-designs/dashboard/img/quota-even.png
  web-console/4.0-designs/dashboard/img/quota-odd.png
Labels: size/S

#138 Updating documentation and moving some items to Future section
  README.md
  web-console/4.0-designs/code-editors/img/2.png
  web-console/4.0-designs/create-from-YAML/create-from-YAML.md
  web-console/4.0-designs/edit-yaml/edit-yaml.md
  web-console/4.0-designs/edit-yaml/img/samples.png
  web-console/4.0-designs/edit-yaml/img/yaml.png
  web-console/4.0-designs/import-yaml/img/YAML-Button.png
  web-console/4.0-designs/import-yaml/img/YAML-Create.png
  web-console/4.0-designs/import-yaml/img/YAML-Error.png
  web-console/4.0-designs/import-yaml/img/YAML-Success.png
  web-console/4.0-designs/import-yaml/img/YAML-Template.png
  web-console/4.0-designs/import-yaml/img/add.png
  web-console/4.0-designs/import-yaml/img/create.png
  web-console/4.0-designs/import-yaml/import-yaml.md
  web-console/4.0-designs/labels/img/Details-1.png
  web-console/4.0-designs/labels/img/Details-2.png
  web-console/4.0-designs/labels/img/Details-3.png
  web-console/4.0-designs/labels/img/expand-4.png
  web-console/4.0-designs/labels/img/styles.png
  web-console/4.0-designs/labels/labels.md
  web-console/4.0-designs/overview/img/overview-empty.png
  web-console/4.0-designs/overview/overview.md
  web-console/futures/bulk-actions/bulk-actions.md
  web-console/futures/bulk-actions/img/3.png
  web-console/futures/bulk-actions/img/4.png
  web-console/futures/bulk-actions/img/5.png
  web-console/futures/code-editor-updates/code-editor-updates.md
  web-console/futures/code-editor-updates/img/1.png
  web-console/futures/code-editor-updates/img/2.png
  web-console/futures/code-editor-updates/img/2b.png
  web-console/futures/code-editor-updates/img/2c.png
  web-console/futures/code-editor-updates/img/3.png
  web-console/futures/code-editor-updates/img/4.png
  web-console/futures/code-editor-updates/img/4b.png
  web-console/futures/code-editor-updates/img/5.png
  web-console/futures/code-editor-updates/img/6.png
  web-console/futures/code-editor-updates/img/7.png
  web-console/futures/code-editor-updates/img/YAML-Button.png
  web-console/futures/code-editor-updates/img/YAML-Create.png
  web-console/futures/code-editor-updates/img/YAML-Error.png
  web-console/futures/code-editor-updates/img/YAML-Success.png
  web-console/futures/code-editor-updates/img/YAML-Template.png
  web-console/futures/code-editor-updates/img/sample.png
  web-console/futures/empty-states/empty-states.md
  web-console/futures/empty-states/img/ES_access.png
  web-console/futures/empty-states/img/ES_create.png
  web-console/futures/empty-states/img/ES_feature.png
  web-console/futures/empty-states/img/ES_filter.png
  web-console/futures/empty-states/img/ES_overview.png
  web-console/futures/project-selector/img/1.1.png
  web-console/futures/project-selector/img/1.png
  web-console/futures/project-selector/project-selector.md
  web-console/futures/quick-start-guide/img/HelpMenu.png
  web-console/futures/quick-start-guide/img/horizontal.png
  web-console/futures/quick-start-guide/img/quick-start-guide.png
  web-console/futures/quick-start-guide/img/vertical.png
  web-console/futures/quick-start-guide/quick-start-guide.md
Labels: size/L

#135 Adding forms documentation
  README.md
  web-console/4.0-designs/forms/forms.md
  web-console/4.0-designs/forms/img/project-crop.png
  web-console/4.0-designs/forms/img/service.png
  web-console/4.0-designs/forms/img/silence-crop.png
  web-console/4.0-designs/forms/img/silence.png
  web-console/4.0-designs/forms/img/storage.png
Labels: size/M
