Repository openshift/openshift-origin-design, pull requests merged in 2018-11, with the labels that each got.

#124 [WIP] Adding documentation for the containers information
  web-console/4.0-designs/containers/containers.md
  web-console/4.0-designs/containers/img/deployment-container.png
  web-console/4.0-designs/containers/img/deployment.png
  web-console/4.0-designs/containers/img/pod-container.png
  web-console/4.0-designs/containers/img/pod.png
Labels: size/M

#129 Adding documentation for the UHC trial flow
  web-console/multi-cluster/trial/img/cluster-trial-1.png
  web-console/multi-cluster/trial/img/cluster-trial-2.png
  web-console/multi-cluster/trial/img/cluster-trial-3.png
  web-console/multi-cluster/trial/img/cluster-trial-4.png
  web-console/multi-cluster/trial/img/cluster-trial-5.png
  web-console/multi-cluster/trial/img/normal-08B.png
  web-console/multi-cluster/trial/trial.md
  web-console/multi-cluster/uhc-create-cluster/img/three-steps.png
  web-console/multi-cluster/uhc-create-cluster/uhc-create-cluster.md
Labels: size/S

#128 Updating about modal in help menu documentation
  web-console/4.0-designs/help-menu/img/about-modal.png
Labels: size/XS

#126 Adding guidelines for Annotations
  README.md
  web-console/4.0-designs/annotations/annotations.md
  web-console/4.0-designs/annotations/img/annotations1.png
  web-console/4.0-designs/annotations/img/annotations2.png
  web-console/4.0-designs/annotations/img/projects-overview.png
Labels: size/M

#130 Fixing Broken Links in the Design Documentation
  README.md
Labels: size/S

#134 Adding cluster settings documentation
  README.md
  web-console/4.0-designs/cluster-settings/cluster-settings.md
  web-console/4.0-designs/cluster-settings/img/edit-channel.png
  web-console/4.0-designs/cluster-settings/img/intro-2.png
  web-console/4.0-designs/cluster-settings/img/intro.png
  web-console/4.0-designs/cluster-settings/img/operators.png
  web-console/4.0-designs/cluster-settings/img/overivew-error.png
  web-console/4.0-designs/cluster-settings/img/overivew-has-update-2.png
  web-console/4.0-designs/cluster-settings/img/overivew-has-update.png
  web-console/4.0-designs/cluster-settings/img/overivew-updating.png
  web-console/4.0-designs/cluster-settings/img/overview-up-to-date.png
  web-console/4.0-designs/cluster-settings/img/upgrade-2.png
  web-console/4.0-designs/cluster-settings/img/upgrade.png
Labels: size/M

#133 Updating trial flow based on feedback
  web-console/multi-cluster/trial/img/new-3-steps.png
  web-console/multi-cluster/trial/trial.md
  web-console/multi-cluster/uhc-create-cluster/img/three-steps.png
Labels: size/S

#131 Add resource quota guidelines
  README.md
  web-console/4.0-designs/resource-quota/img/compute-resources.png
  web-console/4.0-designs/resource-quota/img/quota-details-help.png
  web-console/4.0-designs/resource-quota/img/quota-details.png
  web-console/4.0-designs/resource-quota/img/resource-quota-details.png
  web-console/4.0-designs/resource-quota/img/scopes.png
  web-console/4.0-designs/resource-quota/resource-quota.md
Labels: size/M
