Repository openshift/openshift-origin-design, pull requests merged in 2018-10, with the labels that each got.

#119 Updating READme file
  README.md
Labels: size/XS

#120 Minor updates to the Navigation Documentation on GH
  web-console/4.0-designs/navigation/img/navigation.png
  web-console/4.0-designs/navigation/navigation.md
Labels: size/S

#109 Adding UHC Cluster Documentation
  README.md
  web-console/4.0-designs/uhc-clusters/img/00.png
  web-console/4.0-designs/uhc-clusters/img/01.png
  web-console/4.0-designs/uhc-clusters/img/02.png
  web-console/4.0-designs/uhc-clusters/img/03.png
  web-console/4.0-designs/uhc-clusters/img/04.png
  web-console/4.0-designs/uhc-clusters/uhc-clusters.md
Labels: size/M

#107 Adding guidelines for deploy image in the converged console
  web-console/4.0-designs/deploy-image/deploy-image.md
  web-console/4.0-designs/deploy-image/img/Deploy-Image-All-Projects.png
  web-console/4.0-designs/deploy-image/img/Deploy-Image-Error.png
  web-console/4.0-designs/deploy-image/img/Deploy-Image-Success.png
  web-console/4.0-designs/deploy-image/img/Deploy-Image-Warning.png
  web-console/4.0-designs/deploy-image/img/Deploy-Image.png
  web-console/4.0-designs/deploy-image/img/Deployment-Config.png
Labels: size/M

#111 Adding guidelines for the Project Selector in the converged console
  README.md
  web-console/4.0-designs/project-selector/img/1.1.png
  web-console/4.0-designs/project-selector/img/1.png
  web-console/4.0-designs/project-selector/project-selector.md
Labels: size/S

#112 Paused deployments
  README.md
  web-console/4.0-designs/object-details/img/pause-object.png
  web-console/4.0-designs/object-details/img/resume-object.png
  web-console/4.0-designs/object-details/object-details.md
Labels: size/M

#116 RBAC
  README.md
  web-console/4.0-designs/role-based-access-control/img/action-all.png
  web-console/4.0-designs/role-based-access-control/img/action-single.png
  web-console/4.0-designs/role-based-access-control/img/create-single.png
  web-console/4.0-designs/role-based-access-control/img/details.png
  web-console/4.0-designs/role-based-access-control/img/list-all.png
  web-console/4.0-designs/role-based-access-control/img/list-single.png
  web-console/4.0-designs/role-based-access-control/img/overview-all.png
  web-console/4.0-designs/role-based-access-control/img/overview-single.png
  web-console/4.0-designs/role-based-access-control/img/status-all.png
  web-console/4.0-designs/role-based-access-control/img/status-single.png
  web-console/4.0-designs/role-based-access-control/role-based-access-control.md
Labels: size/M

#113 Adding storage guidelines
  README.md
  web-console/4.0-designs/storage/img/add-storage-create.png
  web-console/4.0-designs/storage/img/add-storage-form.png
  web-console/4.0-designs/storage/img/add-storage.png
  web-console/4.0-designs/storage/img/create-storage-class.png
  web-console/4.0-designs/storage/img/create-storage-form.png
  web-console/4.0-designs/storage/img/storage-class-form.png
  web-console/4.0-designs/storage/img/storage-class-generated-fields.png
  web-console/4.0-designs/storage/img/storage-class-parameters-2.png
  web-console/4.0-designs/storage/img/storage-class-parameters.png
  web-console/4.0-designs/storage/img/storage-class-provisioner.png
  web-console/4.0-designs/storage/storage.md
Labels: size/M

#121 Adding guidelines for Project Overview
  README.md
  web-console/4.0-designs/overview/img/ES_overview.png
  web-console/4.0-designs/overview/img/listview.png
  web-console/4.0-designs/overview/img/overview.png
  web-console/4.0-designs/overview/img/overview2.png
  web-console/4.0-designs/overview/img/resources.png
  web-console/4.0-designs/overview/img/responsive-views.png
  web-console/4.0-designs/overview/img/route.png
  web-console/4.0-designs/overview/overview.md
Labels: size/M

#123 Add binding flow recommendations
  README.md
  web-console/4.0-designs/binding/binding.md
  web-console/4.0-designs/binding/img/add-secret.png
  web-console/4.0-designs/binding/img/binding-details.png
  web-console/4.0-designs/binding/img/binding-pending.png
  web-console/4.0-designs/binding/img/binding-prompt.png
  web-console/4.0-designs/binding/img/binding-ready.png
  web-console/4.0-designs/binding/img/binding-secret.png
  web-console/4.0-designs/binding/img/create-binding.png
Labels: size/S

#125 WIP: Make links relative
  README.md
  web-console/4.0-designs/help-menu/help-menu.md
  web-console/4.0-designs/overview/overview.md
  web-console/homepage/catalog.md
  web-console/homepage/homepage.md
  web-console/homepage/project-panel.md
  web-console/homepage/search-filter.md
  web-console/patterns/masthead.md
  web-console/patterns/navigation.md
  web-console/patterns/notifications.md
  web-console/patterns/order-from-catalog.md
  web-console/project-details/add-to-project.md
  web-console/project-details/binding-details.md
  web-console/project-details/binding-in-project.md
  web-console/project-details/deployment-details.md
  web-console/project-details/in-project-catalog.md
  web-console/project-details/provisioned-service-details.md
  web-console/project-details/provisioned-services-overview.md
  web-console/project-details/provisioned-services.md
  web-console/project-details/quota-warnings.md
Labels: do-not-merge/work-in-progress, size/L
