Repository openshift/openshift-origin-design, pull requests merged in 2019-11, with the labels that each got.

#292 RBAC- for pipeline
  web-console/developer/pipelines/img/RBAC-PL-Details-Overview-Actions.png
  web-console/developer/pipelines/img/RBAC-PL-Details-PLR-Actions.png
  web-console/developer/pipelines/img/RBAC-PL-Details-Parameters.png
  web-console/developer/pipelines/img/RBAC-PL-Details-Resources.png
  web-console/developer/pipelines/img/RBAC-PL-Details-YAML.png
  web-console/developer/pipelines/img/RBAC-PL-ListView.png
  web-console/developer/pipelines/img/RBAC-PLR-Details-Actions.png
  web-console/developer/pipelines/pipelines.md
  web-console/developer/pipelines/rbac-pipelines.md
Labels: size/M

#270 VM-boot-order
  web-console/knikubevirt/knikubevirt.md
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-0-0.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-1-0.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-1-2.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-2-0.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-2-1.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-3-0.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-3-1.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-3-2.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-3-3.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C2-0-0.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C2-0-1.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C2-1-0.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/vm-boot-order.md
Labels: size/M

#294 Fix image url typo in boot order design
  web-console/knikubevirt/vm-details/vm-boot-order/vm-boot-order.md
Labels: size/XS

#276 Aligning VM scheduling snapshot to match PVCs schedule
  web-console/knikubevirt/snapshots/img/1-00.jpg
  web-console/knikubevirt/snapshots/img/1-00.png
  web-console/knikubevirt/snapshots/img/1-01.jpg
  web-console/knikubevirt/snapshots/img/1-01.png
  web-console/knikubevirt/snapshots/img/1-02.jpg
  web-console/knikubevirt/snapshots/img/1-02.png
  web-console/knikubevirt/snapshots/img/1-03.jpg
  web-console/knikubevirt/snapshots/img/1-03.png
  web-console/knikubevirt/snapshots/img/1-04.jpg
  web-console/knikubevirt/snapshots/img/1-04.png
  web-console/knikubevirt/snapshots/img/1-05.jpg
  web-console/knikubevirt/snapshots/img/1-05.png
  web-console/knikubevirt/snapshots/img/1-06.jpg
  web-console/knikubevirt/snapshots/img/1-06.png
  web-console/knikubevirt/snapshots/img/1-07.jpg
  web-console/knikubevirt/snapshots/img/1-07.png
  web-console/knikubevirt/snapshots/img/2-00.jpg
  web-console/knikubevirt/snapshots/img/2-01.jpg
  web-console/knikubevirt/snapshots/img/2-02.jpg
  web-console/knikubevirt/snapshots/img/2-02a.jpg
  web-console/knikubevirt/snapshots/img/2-03.jpg
  web-console/knikubevirt/snapshots/img/2-04.jpg
  web-console/knikubevirt/snapshots/img/3-00.jpg
  web-console/knikubevirt/snapshots/img/3-01.jpg
  web-console/knikubevirt/snapshots/img/3-02.jpg
  web-console/knikubevirt/snapshots/img/3-03.jpg
  web-console/knikubevirt/snapshots/img/4-0.jpg
  web-console/knikubevirt/snapshots/snapshots.md
Labels: size/M

#265 Adding bulk actions documentation
  web-console/future-openshift/bulk-actions/bulk-actions.md
  web-console/future-openshift/bulk-actions/img/1.png
  web-console/future-openshift/bulk-actions/img/2.png
  web-console/future-openshift/bulk-actions/img/3.png
  web-console/future-openshift/bulk-actions/img/4.png
  web-console/future-openshift/bulk-actions/img/add-annotations.png
  web-console/future-openshift/bulk-actions/img/add-labels.png
  web-console/future-openshift/bulk-actions/img/delete-resources.png
Labels: size/M

#264 Adding toolbars documentation
  web-console/future-openshift/toolbars/img/deployments-today.png
  web-console/future-openshift/toolbars/img/events-today.png
  web-console/future-openshift/toolbars/img/explorer-today.png
  web-console/future-openshift/toolbars/img/logs-today.png
  web-console/future-openshift/toolbars/img/nodes-future.png
  web-console/future-openshift/toolbars/img/nodes-today.png
  web-console/future-openshift/toolbars/img/pods-today.png
  web-console/future-openshift/toolbars/img/search-today.png
  web-console/future-openshift/toolbars/img/terminal-today.png
  web-console/future-openshift/toolbars/img/yaml-today.png
  web-console/future-openshift/toolbars/toolbars.md
Labels: size/M

#288 Adding health checks designs
  web-console/future-openshift/health-checks/health-checks.md
  web-console/future-openshift/health-checks/img/C1.png
  web-console/future-openshift/health-checks/img/C2.png
  web-console/future-openshift/health-checks/img/C3.png
  web-console/future-openshift/health-checks/img/C4.png
  web-console/future-openshift/health-checks/img/overview-panel.png
  web-console/future-openshift/health-checks/img/overview.png
Labels: size/S

#267 Adding search page documentation
  web-console/future-openshift/search/img/actions.png
  web-console/future-openshift/search/img/add-annotations.png
  web-console/future-openshift/search/img/add-labels.png
  web-console/future-openshift/search/img/delete-resources.png
  web-console/future-openshift/search/img/empty-state.png
  web-console/future-openshift/search/img/expanded-list0.png
  web-console/future-openshift/search/img/expanded-list1.png
  web-console/future-openshift/search/img/expanded-list4.png
  web-console/future-openshift/search/img/filter1.png
  web-console/future-openshift/search/img/filter2.png
  web-console/future-openshift/search/img/filter3.png
  web-console/future-openshift/search/img/filter4.png
  web-console/future-openshift/search/search.md
Labels: size/M

#293 Adding 4.4 section to the repo and minor reorganization
  README.md
  web-console/future-openshift/favoriting/favoriting.md
  web-console/future-openshift/favoriting/img/dropdown.png
  web-console/future-openshift/favoriting/img/projects1.png
  web-console/future-openshift/favoriting/img/projects2.png
  web-console/future-openshift/favoriting/img/roles1.png
  web-console/future-openshift/favoriting/img/roles2.png
Labels: size/M

#282 Adding custom catalogs to OperatorHub
  README.md
  web-console/future-openshift/custom-catalogs/custom-catalogs.md
  web-console/future-openshift/custom-catalogs/img/operatorhub-custom-catalog1.png
  web-console/future-openshift/custom-catalogs/img/operatorhub-custom-catalog10.png
  web-console/future-openshift/custom-catalogs/img/operatorhub-custom-catalog11.png
  web-console/future-openshift/custom-catalogs/img/operatorhub-custom-catalog12.png
  web-console/future-openshift/custom-catalogs/img/operatorhub-custom-catalog13.png
  web-console/future-openshift/custom-catalogs/img/operatorhub-custom-catalog14.png
  web-console/future-openshift/custom-catalogs/img/operatorhub-custom-catalog2.png
  web-console/future-openshift/custom-catalogs/img/operatorhub-custom-catalog3.png
  web-console/future-openshift/custom-catalogs/img/operatorhub-custom-catalog4.png
  web-console/future-openshift/custom-catalogs/img/operatorhub-custom-catalog5.png
  web-console/future-openshift/custom-catalogs/img/operatorhub-custom-catalog6.png
  web-console/future-openshift/custom-catalogs/img/operatorhub-custom-catalog7.png
  web-console/future-openshift/custom-catalogs/img/operatorhub-custom-catalog8.png
  web-console/future-openshift/custom-catalogs/img/operatorhub-custom-catalog9.png
Labels: size/M

#296 Add OpenShift 4.3 Dashboard documentation
  README.md
  web-console/dashboards/4.3/4.3-dashboards.md
  web-console/dashboards/4.3/4.3-dashboards.sketch
  web-console/dashboards/4.3/img/card-activity-0.png
  web-console/dashboards/4.3/img/card-activity-1a-ongoing-parts.png
  web-console/dashboards/4.3/img/card-activity-1b-status-popover.png
  web-console/dashboards/4.3/img/card-activity-2-event-parts.png
  web-console/dashboards/4.3/img/card-activity-3-states.png
  web-console/dashboards/4.3/img/card-breakdown-0.png
  web-console/dashboards/4.3/img/card-breakdown-1-fewer.png
  web-console/dashboards/4.3/img/card-breakdown-2-states.png
  web-console/dashboards/4.3/img/card-chart-0.png
  web-console/dashboards/4.3/img/card-details-0.png
  web-console/dashboards/4.3/img/card-details-1-parts.png
  web-console/dashboards/4.3/img/card-details-2-states.png
  web-console/dashboards/4.3/img/card-inventory-0.png
  web-console/dashboards/4.3/img/card-inventory-1-parts.png
  web-console/dashboards/4.3/img/card-inventory-2-expansion.png
  web-console/dashboards/4.3/img/card-inventory-3-states.png
  web-console/dashboards/4.3/img/card-status-0.png
  web-console/dashboards/4.3/img/card-status-1-actions.png
  web-console/dashboards/4.3/img/card-status-2a-statuses.png
  web-console/dashboards/4.3/img/card-status-2b-status-popovers.png
  web-console/dashboards/4.3/img/card-status-3-alerts-messages.png
  web-console/dashboards/4.3/img/card-status-4-states.png
  web-console/dashboards/4.3/img/card-utilization-0.png
  web-console/dashboards/4.3/img/card-utilization-1-parts.png
  web-console/dashboards/4.3/img/card-utilization-2b-popovers.png
  web-console/dashboards/4.3/img/card-utilization-3-states.png
  web-console/dashboards/4.3/img/host-0.png
  web-console/dashboards/4.3/img/host-1-inventory.png
  web-console/dashboards/4.3/img/node-0.png
  web-console/dashboards/4.3/img/obj-service-0.png
  web-console/dashboards/4.3/img/overview-0.png
  web-console/dashboards/4.3/img/overview-1a-details-diff.png
  web-console/dashboards/4.3/img/overview-1b-inventory-diff.png
  web-console/dashboards/4.3/img/overview-1c-1-statuses.png
  web-console/dashboards/4.3/img/overview-1c-2-popovers.png
  web-console/dashboards/4.3/img/overview-1c-3-alerts-messages.png
  web-console/dashboards/4.3/img/overview-1c-4-breakdown.png
  web-console/dashboards/4.3/img/overview-1d-1-utilization.png
  web-console/dashboards/4.3/img/overview-1d-2-popovers.png
  web-console/dashboards/4.3/img/overview-2-errors.png
  web-console/dashboards/4.3/img/overview-3-upgrade.png
  web-console/dashboards/4.3/img/overview-4-midupgrade.png
  web-console/dashboards/4.3/img/pers-storage-1-hyperconverged.png
  web-console/dashboards/4.3/img/pers-storage-2-independent.png
  web-console/dashboards/4.3/img/pers-storage-3-breakdowns.png
  web-console/dashboards/4.3/img/project-0a-healthy.png
  web-console/dashboards/4.3/img/project-0b-quotas.png
  web-console/dashboards/4.3/img/project-1-dev.png
  web-console/dashboards/4.3/img/vm-0.png
  web-console/dashboards/4.3/img/vm-1-statuses.png
  web-console/knikubevirt/knikubevirt.md
Labels: size/L

#297 Add serverless link to topology
  web-console/developer/topology/topology-serverless.md
  web-console/developer/topology/topology-serverless/img/EventSource-Filter.png
  web-console/developer/topology/topology-serverless/img/EventSource-Overview.png
  web-console/developer/topology/topology-serverless/img/EventSource-Overview_actionsdropdown.png
  web-console/developer/topology/topology-serverless/img/EventSource-Resources.png
  web-console/developer/topology/topology-serverless/img/EventSource-inanotherapp.png
  web-console/developer/topology/topology-serverless/img/EventSource-unassigned.png
  web-console/developer/topology/topology-serverless/img/EventSource.png
  web-console/developer/topology/topology-serverless/topology-serverless.md
  web-console/developer/topology/topology.md
Labels: size/M

#300 Update add and new add pipeline
  web-console/developer/add/add.md
  web-console/developer/add/sections/pipelines/img/+Add_Flow_Add_Pipe.png
  web-console/developer/add/sections/pipelines/img/+Add_Flow_Pipelines_Docker_No_Temp.png
  web-console/developer/add/sections/pipelines/img/+Add_Flow_Pipelines_ImportFromGit.png
  web-console/developer/add/sections/pipelines/img/+Add_Flow_Pipelines_ImportFromGit_No_Img.png
  web-console/developer/add/sections/pipelines/img/+Add_Flow_Pipelines_ImportFromGit_No_Temp.png
  web-console/developer/add/sections/pipelines/img/+Add_Flow_Show_Pipe_Viz.png
  web-console/developer/add/sections/pipelines/img/+Add_Flow_Showing_Pipe_Viz.png
  web-console/developer/add/sections/pipelines/pipelines.md
Labels: size/L

#298 VM boot order
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-0-0.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-1-0.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-1-2.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-2-0.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-2-1.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-3-0.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-3-1.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-3-2.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C1-3-3.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C2-0-0.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C2-0-1.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/C2-1-0.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/Spec-Modal-drag&drop 01.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/Spec-Modal-empty-state-01.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/Spec-Modal-list-01.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/img/Spec-inpage-01.jpg
  web-console/knikubevirt/vm-details/vm-boot-order/vm-boot-order.md
Labels: size/M
