Repository openshift/openshift-origin-design, pull requests merged in 2019-09, with the labels that each got.

#269 Fixed broken link for object storage dashboard
  README.md
Labels: size/XS

#260 adds edit CD
  web-console/knikubevirt/vm-details/img/cd-edit.png
  web-console/knikubevirt/vm-details/img/cd-field.png
  web-console/knikubevirt/vm-details/img/edit-blank.png
  web-console/knikubevirt/vm-details/img/edit-container-windows-2.png
  web-console/knikubevirt/vm-details/img/edit-container-windows.png
  web-console/knikubevirt/vm-details/img/edit-container.png
  web-console/knikubevirt/vm-details/img/edit-pvc.png
  web-console/knikubevirt/vm-details/img/edit-url.png
  web-console/knikubevirt/vm-details/vm-details.md
Labels: size/M

#262 Create A Virtual Machine - Step 4: Advanced
  web-console/knikubevirt/Create-vm/step-4-advanced/img/alert-notification.png
  web-console/knikubevirt/Create-vm/step-4-advanced/img/customscript.png
  web-console/knikubevirt/Create-vm/step-4-advanced/img/guest-agent-installer-on.png
  web-console/knikubevirt/Create-vm/step-4-advanced/img/ssh-keys.png
  web-console/knikubevirt/Create-vm/step-4-advanced/wizard-advanced.md
Labels: size/M

#258 Further exploration into states of VM in wizard
  web-console/knikubevirt/Create-vm/step-5-review/img/Icon 
  web-console/knikubevirt/Create-vm/step-5-review/img/alert-toast-notification.png
  web-console/knikubevirt/Create-vm/step-5-review/img/error-popover.png
  web-console/knikubevirt/Create-vm/step-5-review/img/fixed-and-creating.png
  web-console/knikubevirt/Create-vm/step-5-review/img/vm-starting.png
  web-console/knikubevirt/Create-vm/step-5-review/wizard-review.md
  web-console/knikubevirt/Create-vm/step-6-results/img/Icon 
  web-console/knikubevirt/Create-vm/step-6-results/img/alert-toast-notification.png
  web-console/knikubevirt/Create-vm/step-6-results/img/create-vm-inline-wizard-error.png
  web-console/knikubevirt/Create-vm/step-6-results/img/create-vm-inline-wizard-in-progress.png
  web-console/knikubevirt/Create-vm/step-6-results/img/create-vm-inline-wizard-input.png
  web-console/knikubevirt/Create-vm/step-6-results/img/create-vm-inline-wizard-success.png
  web-console/knikubevirt/Create-vm/step-6-results/img/error-inline.png
  web-console/knikubevirt/Create-vm/step-6-results/img/error-popover.png
  web-console/knikubevirt/Create-vm/step-6-results/img/vm-starting-state.png
  web-console/knikubevirt/Create-vm/step-6-results/wizard-results.md
  web-console/knikubevirt/knikubevirt.md
Labels: size/M

#257 add port bindings
  web-console/knikubevirt/Create-vm/step-2-networking/create-vm-networking.md
  web-console/knikubevirt/Create-vm/step-2-networking/img/3-00.png
  web-console/knikubevirt/Create-vm/step-2-networking/img/3-01.png
  web-console/knikubevirt/Create-vm/step-2-networking/img/3-02.png
  web-console/knikubevirt/Create-vm/step-2-networking/img/3-03.png
  web-console/knikubevirt/Create-vm/step-2-networking/img/3-10.png
  web-console/knikubevirt/Create-vm/step-2-networking/img/3-20.png
Labels: size/S

#226 Affinity rules
  web-console/knikubevirt/Affinity/affinity.md
  web-console/knikubevirt/Affinity/img/E1-0-0.jpg
  web-console/knikubevirt/Affinity/img/E1-1-0.jpg
  web-console/knikubevirt/Affinity/img/E1-1-1.jpg
  web-console/knikubevirt/Affinity/img/E1-1-2.jpg
  web-console/knikubevirt/Affinity/img/E1-1-3.jpg
  web-console/knikubevirt/Affinity/img/E2-0-0.jpg
  web-console/knikubevirt/knikubevirt.md
Labels: size/M

#250 Add cron job designs
  README.md
  web-console/future-openshift/cron-jobs/cron-jobs.md
  web-console/future-openshift/cron-jobs/img/create-cron-job-2.png
  web-console/future-openshift/cron-jobs/img/create-cron-job.png
  web-console/future-openshift/cron-jobs/img/cron-job-jobs.png
  web-console/future-openshift/cron-jobs/img/cron-job-list.png
  web-console/future-openshift/cron-jobs/img/cron-job-resume.png
  web-console/future-openshift/cron-jobs/img/cron-job-suspend.png
  web-console/future-openshift/cron-jobs/img/cron-job-suspended.png
Labels: size/S

#251 Update chargeback with report creation form designs
  web-console/future-openshift/chargeback/chargeback.md
  web-console/future-openshift/chargeback/img/create-from-query.png
  web-console/future-openshift/chargeback/img/create-report-2.png
  web-console/future-openshift/chargeback/img/create-report-3.png
  web-console/future-openshift/chargeback/img/create-report-4.png
  web-console/future-openshift/chargeback/img/create-report-5.png
  web-console/future-openshift/chargeback/img/create-report.png
  web-console/future-openshift/chargeback/img/queries-list-create.png
  web-console/future-openshift/chargeback/img/queries-list.png
  web-console/future-openshift/chargeback/img/reports-list.png
Labels: size/M

#272 Adding link to OCM mockups
  README.md
Labels: size/XS

#277 minor update
  web-console/knikubevirt/Create-vm/step-3-storage/wizard-storage.md
Labels: size/XS

#225 Expand OCS Cluster
  web-console/4.0-designs/storage/Expand Storage Cluster/Expand Storage Cluster.md
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Create-Node-01.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Create-Node-02.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-00.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-01.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-02.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-03.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-04.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-05.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-06.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-07.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-08.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-09.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-10.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-11.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-12.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-13.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-14.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-15.png
  web-console/4.0-designs/storage/Expand Storage Cluster/img/Expand-Storage-16.png
Labels: size/M

#275 Updates for OB/OBC management
  web-console/Storage/OB-OB-Lifecycle-Management/OB-OBC-Lifecycle.md
  web-console/Storage/OB-OB-Lifecycle-Management/img/OB-create.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OB-list.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OB-overview.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OBC-attach-pod-01.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OBC-attach-pod.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OBC-create.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OBC-delete-obc.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OBC-list.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OBC-overview.png
Labels: size/M
