Repository openshift/openshift-origin-design, pull requests merged in 2019-06, with the labels that each got.

#182 Link between PVC and VM Disk
  web-console/knikubevirt/expose-secret/img/add-secret-to-vm.png
  web-console/knikubevirt/guest-agent-not-installed/img/OLD/guest-agent-1.png
  web-console/knikubevirt/link-between-PVC-VMdisk/img/linking-pvc-to-disk.png
  web-console/knikubevirt/link-between-PVC-VMdisk/img/pvc-details-highlight-row.png
  web-console/knikubevirt/link-between-PVC-VMdisk/img/pvc-details.png
  web-console/knikubevirt/link-between-PVC-VMdisk/link-between-PVC-VMdisk.md
Labels: size/S

#193 Expose Secrets, Config Maps and Service Accounts
  web-console/knikubevirt/expose-secret/expose-secret.md
  web-console/knikubevirt/expose-secret/img/add-as-disk.png
  web-console/knikubevirt/expose-secret/img/add-as-open-dropdown.png
  web-console/knikubevirt/expose-secret/img/add-dropdown-open.png
  web-console/knikubevirt/expose-secret/img/add-to-workload-popup-open-dropdown.png
  web-console/knikubevirt/expose-secret/img/add-to-workload-popup.png
  web-console/knikubevirt/expose-secret/img/add-to-workload.png
  web-console/knikubevirt/expose-secret/img/add.png
  web-console/knikubevirt/expose-secret/img/environment-tab.png
  web-console/knikubevirt/expose-secret/img/expose-from-accounts-list.png
  web-console/knikubevirt/expose-secret/img/expose-from-detailed-page-popup.png
  web-console/knikubevirt/expose-secret/img/expose-from-detailed-page.png
Labels: size/M

#198 Add links for Exposing Secrets and PVC/VM Disk Link
  README.md
Labels: size/XS

#196 Updating project details view
  README.md
  web-console/future-openshift/dashboards/dashboards.md
  web-console/future-openshift/dashboards/img/2-overview-dashboard.png
  web-console/future-openshift/dashboards/img/2-resources-empty-state.png
  web-console/future-openshift/dashboards/img/2-resources.png
Labels: size/M

#194 Add link to "guest agent not installed" on the Readme.md file
  README.md
Labels: size/XS

#171 Adding services in overview
  web-console/knikubevirt/expose-vm-as-a-service/expose-vm-as-a-service.md
Labels: size/XS

#200 VM details
  README.md
  web-console/knikubevirt/vm-details/img/1-0-0.jpg
  web-console/knikubevirt/vm-details/img/1-0-1.jpg
  web-console/knikubevirt/vm-details/img/2-0-0.jpg
  web-console/knikubevirt/vm-details/img/2-0-1.jpg
  web-console/knikubevirt/vm-details/img/2-0-2.jpg
  web-console/knikubevirt/vm-details/img/2-0-3.jpg
  web-console/knikubevirt/vm-details/img/2-0-4.jpg
  web-console/knikubevirt/vm-details/img/2-0-5.jpg
  web-console/knikubevirt/vm-details/img/2-0-6.jpg
  web-console/knikubevirt/vm-details/img/2-1-0.jpg
  web-console/knikubevirt/vm-details/img/2-1-1.jpg
  web-console/knikubevirt/vm-details/img/2-1-2.jpg
  web-console/knikubevirt/vm-details/img/3-0-0.jpg
  web-console/knikubevirt/vm-details/img/3-1-0.jpg
  web-console/knikubevirt/vm-details/img/3-2-0.jpg
  web-console/knikubevirt/vm-details/img/4-0-0.jpg
  web-console/knikubevirt/vm-details/img/4-1-0.jpg
  web-console/knikubevirt/vm-details/img/4-2-0.jpg
  web-console/knikubevirt/vm-details/img/4-3-0.jpg
  web-console/knikubevirt/vm-details/img/4-4-0.jpg
  web-console/knikubevirt/vm-details/img/4-5-0.jpg
  web-console/knikubevirt/vm-details/img/4-6-0.jpg
  web-console/knikubevirt/vm-details/vm-details.md
Labels: size/L

#199 Adding IDP forms to OAuth documentation
  web-console/future-openshift/oauth/img/HTPasswd.png
  web-console/future-openshift/oauth/img/basic.png
  web-console/future-openshift/oauth/img/github.png
  web-console/future-openshift/oauth/img/gitlab.png
  web-console/future-openshift/oauth/img/google.png
  web-console/future-openshift/oauth/img/keystone.png
  web-console/future-openshift/oauth/img/ldap.png
  web-console/future-openshift/oauth/img/openID.png
  web-console/future-openshift/oauth/img/request.png
  web-console/future-openshift/oauth/oauth.md
Labels: size/S

#202 Add metrics page designs and guidelines
  README.md
  web-console/monitoring/metrics/img/metrics-add-query.png
  web-console/monitoring/metrics/img/metrics-autocomplete-2.png
  web-console/monitoring/metrics/img/metrics-autocomplete.png
  web-console/monitoring/metrics/img/metrics-dropdown.png
  web-console/monitoring/metrics/img/metrics-empty.png
  web-console/monitoring/metrics/img/metrics-error.png
  web-console/monitoring/metrics/img/metrics-full.png
  web-console/monitoring/metrics/img/metrics-hide-query.png
  web-console/monitoring/metrics/img/metrics-hide-series.png
  web-console/monitoring/metrics/img/metrics-results.png
  web-console/monitoring/metrics/metrics.md
Labels: size/M

#203 Add Alertmanager config editor designs
  README.md
  web-console/monitoring/alertmanager-config/alertmanager-config.md
  web-console/monitoring/alertmanager-config/img/alerts-list.png
  web-console/monitoring/alertmanager-config/img/config-dropdown.png
  web-console/monitoring/alertmanager-config/img/config-empty.png
  web-console/monitoring/alertmanager-config/img/create-default-receiver.png
  web-console/monitoring/alertmanager-config/img/create-receiver-long.png
  web-console/monitoring/alertmanager-config/img/create-receiver-short.png
  web-console/monitoring/alertmanager-config/img/edit-receiver.png
  web-console/monitoring/alertmanager-config/img/edit-yaml.png
Labels: size/M

#184 Create Virtual Machine
  README.md
  web-console/knikubevirt/Create-vm/create-vm.md
  web-console/knikubevirt/Create-vm/img/Step-1-basic-Flavour.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-ISO-2.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-ISO.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-Image-1.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-Image-2.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-Operating-system-1.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-Operating-system-2.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-Operating-system-3.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-PXE-1.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-appliance-1.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-appliance-2.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-attach-disk-dropdown.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-attach-disk-selected.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-attach-disk.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-container.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-namespace.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-no-template-chosen.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-template-2.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-template-3 Copy.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-template-3.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-template-4.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-template.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-url.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-workload-profile.png
Labels: size/L

#210 little updates
  README.md
Labels: size/XS

#213 Fix Status Popover image grammar
  web-console/4.0-designs/status/img/status-popover-table.png
Labels: size/XS

#216 update readme
  README.md
Labels: size/XS

#204 Import flow
  README.md
  web-console/knikubevirt/import-vm/img/Import-vm.png
  web-console/knikubevirt/import-vm/img/Step-1-basic-import-0.png
  web-console/knikubevirt/import-vm/img/Step-1-basic-import-1.png
  web-console/knikubevirt/import-vm/img/Step-1-basic-import-2.png
  web-console/knikubevirt/import-vm/img/Step-1-basic-import-3.png
  web-console/knikubevirt/import-vm/img/Step-1-basic-import-4.1.png
  web-console/knikubevirt/import-vm/img/Step-1-basic-import-4.2.png
  web-console/knikubevirt/import-vm/img/Step-1-basic-import-4.3.png
  web-console/knikubevirt/import-vm/img/Step-1-basic-import-4.png
  web-console/knikubevirt/import-vm/img/Step-1-basic-import-5.png
  web-console/knikubevirt/import-vm/img/Step-1-basic-import-6.png
  web-console/knikubevirt/import-vm/img/Step-1-basic-import-7.1.png
  web-console/knikubevirt/import-vm/img/Step-1-basic-import-7.png
  web-console/knikubevirt/import-vm/img/Step-1-basic-import-8.1.png
  web-console/knikubevirt/import-vm/img/Step-1-basic-import-8.png
  web-console/knikubevirt/import-vm/import-vm.md
Labels: size/M

#212 Updating documentation organization
  README.md
  web-console/knikubevirt/clone-vm/clone-vm.md
  web-console/knikubevirt/knikubevirt.md
  web-console/knikubevirt/migrate-vm/migrate-vm.md
Labels: size/L

#217 removes console item
  web-console/knikubevirt/knikubevirt.md
Labels: size/XS
