Repository openshift/openshift-origin-design, pull requests merged in 2019-03, with the labels that each got.

#147 Add designs for an alert metrics chart
  web-console/monitoring/alerts/alerts.md
  web-console/monitoring/alerts/img/alert-metrics-drag.png
  web-console/monitoring/alerts/img/alert-metrics-zoom.png
  web-console/monitoring/alerts/img/alert-metrics.png
  web-console/monitoring/alerts/img/alert-rule-metrics.png
Labels: size/S

#153 Nodes list view designs
  web-console/future-openshift/nodes/img/mobile.png
  web-console/future-openshift/nodes/img/nodes-expanded.png
  web-console/future-openshift/nodes/img/nodes.png
  web-console/future-openshift/nodes/nodes.md
Labels: size/S

#152 Updating cluster settings updates flow
  web-console/4.0-designs/cluster-settings/cluster-settings.md
  web-console/4.0-designs/cluster-settings/img/intro-2.png
  web-console/4.0-designs/cluster-settings/img/overivew-error.png
  web-console/4.0-designs/cluster-settings/img/overivew-has-update-2.png
  web-console/4.0-designs/cluster-settings/img/overivew-has-update.png
  web-console/4.0-designs/cluster-settings/img/overivew-updating.png
  web-console/4.0-designs/cluster-settings/img/overview-up-to-date.png
  web-console/4.0-designs/cluster-settings/img/overview.png
  web-console/4.0-designs/cluster-settings/img/up-to-date.png
  web-console/4.0-designs/cluster-settings/img/update-available.png
  web-console/4.0-designs/cluster-settings/img/update-failing.png
  web-console/4.0-designs/cluster-settings/img/update-in-progress.png
  web-console/4.0-designs/cluster-settings/img/update-modal.png
  web-console/4.0-designs/cluster-settings/img/upgrade-2.png
Labels: size/M

#157 Adding machines page
  README.md
  web-console/future-openshift/machines/img/MC-Details.png
  web-console/future-openshift/machines/img/MCP-Details.png
  web-console/future-openshift/machines/img/MCPs.png
  web-console/future-openshift/machines/img/MCs.png
  web-console/future-openshift/machines/img/Machine-Details.png
  web-console/future-openshift/machines/img/Machine-Set-Details.png
  web-console/future-openshift/machines/img/Machine-Set-Machines.png
  web-console/future-openshift/machines/img/Machine-Sets.png
  web-console/future-openshift/machines/img/Machines.png
  web-console/future-openshift/machines/img/Navigation.png
  web-console/future-openshift/machines/machines.md
Labels: size/M

#158 Updating OAuth documentation
  web-console/future-openshift/oauth/img/CS-OAuth.png
  web-console/future-openshift/oauth/img/CS-empty.png
  web-console/future-openshift/oauth/img/CS-idp-overview.png
  web-console/future-openshift/oauth/img/CS-list.png
  web-console/future-openshift/oauth/img/HTPasswd.png
  web-console/future-openshift/oauth/img/openID.png
  web-console/future-openshift/oauth/oauth.md
Labels: needs-rebase, size/M
