Repository openshift/openshift-origin-design, pull requests merged in 2019-05, with the labels that each got.

#161 Adding documentation for operators on the status page
  README.md
  web-console/future-openshift/operators-overview/img/operators8-app.png
  web-console/future-openshift/operators-overview/img/operators8-overview.png
  web-console/future-openshift/operators-overview/img/operators8-resource.png
  web-console/future-openshift/operators-overview/operators-overview.md
Labels: size/S

#162 Adding command line tools documentation
  README.md
  web-console/future-openshift/command-line-tools/command-line-tools.md
  web-console/future-openshift/command-line-tools/img/data-list.png
  web-console/future-openshift/command-line-tools/img/dropdown.png
Labels: size/S

#166 Image commands
  README.md
  web-console/future-openshift/image-commands/image-commands.md
  web-console/future-openshift/image-commands/img/image-stream-popover.png
  web-console/future-openshift/image-commands/img/image-stream-prompt.png
  web-console/future-openshift/image-commands/img/image-stream-tag-popover.png
  web-console/future-openshift/image-commands/img/image-stream-tag-prompt.png
Labels: size/M

#165 Adding favorites documentation
  README.md
  web-console/future-openshift/pinning/img/dropdown.png
  web-console/future-openshift/pinning/img/projects1.png
  web-console/future-openshift/pinning/img/projects2.png
  web-console/future-openshift/pinning/img/roles1.png
  web-console/future-openshift/pinning/img/roles2.png
  web-console/future-openshift/pinning/pinning.md
  web-console/old/project-selector/img/1.1.png
  web-console/old/project-selector/img/1.png
  web-console/old/project-selector/project-selector.md
Labels: size/M

#164 Adding machine deployments and machine health checks
  web-console/future-openshift/machines/img/Navigation.png
  web-console/future-openshift/machines/img/machine-deployments-details.png
  web-console/future-openshift/machines/img/machine-deployments-list.png
  web-console/future-openshift/machines/img/machine-healthchecks-details.png
  web-console/future-openshift/machines/img/machine-healthchecks-list.png
  web-console/future-openshift/machines/machines.md
Labels: size/M

#167 Add dashboard organization guidelines
  README.md
  web-console/future-openshift/dashboards/dashboards.md
  web-console/future-openshift/dashboards/img/cluster-scoped.png
  web-console/future-openshift/dashboards/img/dashboard-navigation.png
  web-console/future-openshift/dashboards/img/project-details.png
  web-console/future-openshift/dashboards/img/project-list.png
Labels: size/M

#170 Adding migrate vm files to knikubevirt
  web-console/knikubevirt/migrate-vm/img/1-0-list.png
  web-console/knikubevirt/migrate-vm/img/1-1-modal-info.png
  web-console/knikubevirt/migrate-vm/img/1-2-modal-migrate.png
  web-console/knikubevirt/migrate-vm/img/1-3-list-notification-started.png
  web-console/knikubevirt/migrate-vm/img/1-4-list-notification-completed.png
  web-console/knikubevirt/migrate-vm/migrate-vm.md
Labels: size/S

#178 Initial commit
  README.md
  web-console/future-openshift/contextual-help/contextual-help.md
  web-console/future-openshift/contextual-help/img/hint-general.png
  web-console/future-openshift/contextual-help/img/hint-new-features.png
  web-console/future-openshift/contextual-help/img/hint-next-step.png
  web-console/future-openshift/contextual-help/img/hint-spacing.png
  web-console/future-openshift/contextual-help/img/infopop-non-obvious.png
  web-console/future-openshift/contextual-help/img/infopop-outside-ui.png
Labels: size/M

#180 Add offline and maintenance status icons
  web-console/4.0-designs/status/img/pficon-maintenance.png
  web-console/4.0-designs/status/img/pficon-off.png
  web-console/4.0-designs/status/status.md
Labels: size/XS

#168 Adding clone-vm design to knikubevirt folder
  web-console/knikubevirt/clone-vm/clone-vm.md
  web-console/knikubevirt/clone-vm/img/3-0-vms.jpg
  web-console/knikubevirt/clone-vm/img/3-1-vm-list.jpg
  web-console/knikubevirt/clone-vm/img/3-2-modal.jpg
  web-console/knikubevirt/clone-vm/img/3-3-vm-list-error.jpg
  web-console/knikubevirt/clone-vm/img/3-4-0-vm-list-cloning.jpg
  web-console/knikubevirt/clone-vm/img/3-4-1-vm-list-cloning-source-popover.jpg
  web-console/knikubevirt/clone-vm/img/3-4-2-vm-list-cloning-source-options.jpg
  web-console/knikubevirt/clone-vm/img/3-4-3-vm-list-cloning-source-stop.jpg
Labels: size/M

#174 guest-agent-not-installed
  web-console/knikubevirt/guest-agent-not-installed/guest-agent-not-installed.md
  web-console/knikubevirt/guest-agent-not-installed/img/guest-agent-1.png
  web-console/knikubevirt/guest-agent-not-installed/img/guest-agent-2.png
Labels: size/XS

#173 Adding vm-templates design
  web-console/knikubevirt/vm-templates/img/1-0-vm-template-list.jpg
  web-console/knikubevirt/vm-templates/img/1-1-0-create-template.jpg
  web-console/knikubevirt/vm-templates/img/1-1-1-create-template-modal.jpg
  web-console/knikubevirt/vm-templates/img/1-2-0-create-template-from-vm-list.jpg
  web-console/knikubevirt/vm-templates/img/1-2-1-create-template-from-vm-list-modal.jpg
  web-console/knikubevirt/vm-templates/img/1-2-2-create-template-from-vm-list-starting.jpg
  web-console/knikubevirt/vm-templates/img/1-3-0-create-template-from-template-list.jpg
  web-console/knikubevirt/vm-templates/img/1-3-1-create-template-from-template-list-modal.jpg
  web-console/knikubevirt/vm-templates/vm-templates.md
Labels: size/M

#181 Add open source license
  LICENSE
Labels: size/L

#179 Add status popover design documentation
  README.md
  web-console/4.0-designs/status/img/status-popover-examples.png
  web-console/4.0-designs/status/img/status-popover-table.png
  web-console/4.0-designs/status/status.md
  web-console/future-openshift/contextual-help/contextual-help.md
Labels: size/S

#188 Add pull request template
  .github/pull_request_template.md
Labels: size/S

#190 Fix PR template wording
  .github/pull_request_template.md
Labels: size/XS

#172 Expose vm as a service
  README.md
  web-console/knikubevirt/expose-vm-as-a-service/expose-vm-as-a-service.md
  web-console/knikubevirt/expose-vm-as-a-service/img/Expose_01.png
  web-console/knikubevirt/expose-vm-as-a-service/img/Expose_010Services.png
  web-console/knikubevirt/expose-vm-as-a-service/img/Expose_02.png
  web-console/knikubevirt/expose-vm-as-a-service/img/Expose_03.png
  web-console/knikubevirt/expose-vm-as-a-service/img/Expose_04_b.png
  web-console/knikubevirt/expose-vm-as-a-service/img/Expose_04a.png
  web-console/knikubevirt/expose-vm-as-a-service/img/Expose_05a.png
  web-console/knikubevirt/expose-vm-as-a-service/img/Expose_05b.png
  web-console/knikubevirt/expose-vm-as-a-service/img/Expose_06.png
  web-console/knikubevirt/expose-vm-as-a-service/img/Expose_07.png
  web-console/knikubevirt/expose-vm-as-a-service/img/Expose_08.png
  web-console/knikubevirt/expose-vm-as-a-service/img/Expose_09.png
Labels: size/M

#187 Linking migrate VM to documentation
  README.md
Labels: size/XS

#191 adding clone-vm LINK to the readme.md
  README.md
Labels: size/XS

#197 Add a link from Expose VM as a Service to MD file
  README.md
Labels: size/XS

#177 Adding YAML switcher and samples panels
  README.md
  web-console/future-openshift/resource-creation/img/both-YAML.png
  web-console/future-openshift/resource-creation/img/both-form.png
  web-console/future-openshift/resource-creation/img/both-form2.png
  web-console/future-openshift/resource-creation/img/no-sample.png
  web-console/future-openshift/resource-creation/img/sample1.png
  web-console/future-openshift/resource-creation/img/sample2.png
  web-console/future-openshift/resource-creation/img/switcher-YAML.png
  web-console/future-openshift/resource-creation/img/switcher-form.png
  web-console/future-openshift/resource-creation/img/switcher-form2.png
  web-console/future-openshift/resource-creation/resource-creation.md
Labels: size/M

#195 Initial PR for dev console
  README.md
  web-console/developer/add/add.md
  web-console/developer/advanced/advanced.md
  web-console/developer/builds/builds.md
  web-console/developer/developer.md
  web-console/developer/pipelines/pipelines.md
  web-console/developer/topology/topology.md
Labels: size/M

#192 adding link to vm-templates PR on the readme.md
  README.md
Labels: size/XS
