Repository openshift/openshift-origin-design, pull requests merged in 2019-07, with the labels that each got.

#224 move vm details
  web-console/knikubevirt/knikubevirt.md
Labels: size/XS

#221 Adding links to GDocs for awareness to dev perspective designs
  web-console/developer/add/add.md
  web-console/developer/add/img/dev-add.png
  web-console/developer/add/img/import-yaml.png
  web-console/developer/advanced/advanced.md
  web-console/developer/builds/builds.md
  web-console/developer/developer.md
  web-console/developer/img/dev-nav.png
  web-console/developer/pipelines/pipelines.md
  web-console/developer/topology/topology.md
Labels: size/M

#183 VM snapshots -WIP
  web-console/knikubevirt/knikubevirt.md
  web-console/knikubevirt/snapshots/img/1-00.jpg
  web-console/knikubevirt/snapshots/img/1-00.png
  web-console/knikubevirt/snapshots/img/1-01.jpg
  web-console/knikubevirt/snapshots/img/1-01.png
  web-console/knikubevirt/snapshots/img/1-02.jpg
  web-console/knikubevirt/snapshots/img/1-02.png
  web-console/knikubevirt/snapshots/img/1-03.jpg
  web-console/knikubevirt/snapshots/img/1-03.png
  web-console/knikubevirt/snapshots/img/1-04.jpg
  web-console/knikubevirt/snapshots/img/1-04.png
  web-console/knikubevirt/snapshots/img/1-05.jpg
  web-console/knikubevirt/snapshots/img/1-05.png
  web-console/knikubevirt/snapshots/img/1-06.jpg
  web-console/knikubevirt/snapshots/img/1-06.png
  web-console/knikubevirt/snapshots/img/1-07.jpg
  web-console/knikubevirt/snapshots/img/1-07.png
  web-console/knikubevirt/snapshots/img/2-00.jpg
  web-console/knikubevirt/snapshots/img/2-01.jpg
  web-console/knikubevirt/snapshots/img/2-02.jpg
  web-console/knikubevirt/snapshots/img/2-02a.jpg
  web-console/knikubevirt/snapshots/img/2-03.jpg
  web-console/knikubevirt/snapshots/img/2-04.jpg
  web-console/knikubevirt/snapshots/img/3-00.jpg
  web-console/knikubevirt/snapshots/img/3-01.jpg
  web-console/knikubevirt/snapshots/img/3-02.jpg
  web-console/knikubevirt/snapshots/img/3-03.jpg
  web-console/knikubevirt/snapshots/img/3-04.jpg
  web-console/knikubevirt/snapshots/img/4-0.jpg
  web-console/knikubevirt/snapshots/snapshots.md
Labels: size/M

#205 List view in PF4
  web-console/knikubevirt/vm-list/img/0-0-main.png
  web-console/knikubevirt/vm-list/img/0-0a-tooltips.png
  web-console/knikubevirt/vm-list/img/1-0-filtering.png
  web-console/knikubevirt/vm-list/img/1-1-filtering-name.png
  web-console/knikubevirt/vm-list/img/1-2-filtering-search-ip.png
  web-console/knikubevirt/vm-list/img/1-3-filtering-search-status.png
  web-console/knikubevirt/vm-list/img/2-0-sort-name.png
  web-console/knikubevirt/vm-list/img/2-1-sort-node.png
  web-console/knikubevirt/vm-list/img/2-2-sort-node-reverse.png
  web-console/knikubevirt/vm-list/img/3-0-selected-vm-off.png
  web-console/knikubevirt/vm-list/img/3-1-0-selected-vm-running-power.png
  web-console/knikubevirt/vm-list/img/3-1-1a-power-modal-suspend.png
  web-console/knikubevirt/vm-list/img/3-1-1b-power-modal-restart.png
  web-console/knikubevirt/vm-list/img/3-1-1c-power-modal-shut-down.png
  web-console/knikubevirt/vm-list/img/3-2-selected-vm-running-consoles.png
  web-console/knikubevirt/vm-list/img/3-3-selected-vm-transitioning.png
  web-console/knikubevirt/vm-list/img/confirmationmodal.png
  web-console/knikubevirt/vm-list/img/connecttoconsoledropdown.png
  web-console/knikubevirt/vm-list/img/dropdownpower.png
  web-console/knikubevirt/vm-list/img/itemfiltererror.png
  web-console/knikubevirt/vm-list/img/restartmodal.png
  web-console/knikubevirt/vm-list/img/searchfilter.png
  web-console/knikubevirt/vm-list/img/shutdownmodal.png
  web-console/knikubevirt/vm-list/img/sorting.png
  web-console/knikubevirt/vm-list/img/sorting2.png
  web-console/knikubevirt/vm-list/img/statuspopovers.png
  web-console/knikubevirt/vm-list/img/transitionalstatemenu.png
  web-console/knikubevirt/vm-list/img/vmlist.png
  web-console/knikubevirt/vm-list/img/vmlistdropdownoff.png
  web-console/knikubevirt/vm-list/list-view.md
  web-console/knikubevirt/vm-list/vm-list.md
Labels: size/L

#218 Openshift VMs overview
  web-console/knikubevirt/openshift-vms-overview/Openshift-overview-virtual-machine-dropdown.png
  web-console/knikubevirt/openshift-vms-overview/Openshift-overview-virtual-machine-overviewtab.png
  web-console/knikubevirt/openshift-vms-overview/Openshift-overview-virtual-machine-resourcetab.png
  web-console/knikubevirt/openshift-vms-overview/Openshift-overview-virtual-machine-sparkline.png
  web-console/knikubevirt/openshift-vms-overview/openshift-vms-overview.md
Labels: size/S

#229 Fix broken link list view
  web-console/knikubevirt/vm-list/vm-list.md
Labels: size/XS

#231 add link
  web-console/knikubevirt/knikubevirt.md
  web-console/knikubevirt/openshift-vms-overview/openshift-vms-overview.md
Labels: size/XS

#232 import link added
  web-console/knikubevirt/knikubevirt.md
Labels: size/XS

#223 Adding explorer designs for 4.2
  README.md
  web-console/future-openshift/api-explorer/api-explorer.md
  web-console/future-openshift/api-explorer/img/buildconfig-samples.png
  web-console/future-openshift/api-explorer/img/buildconfig-schema.png
  web-console/future-openshift/api-explorer/img/buildconfig.png
  web-console/future-openshift/api-explorer/img/full-access.png
  web-console/future-openshift/api-explorer/img/full-instances.png
  web-console/future-openshift/api-explorer/img/full-overview.png
  web-console/future-openshift/api-explorer/img/full-samples.png
  web-console/future-openshift/api-explorer/img/full-schema.png
  web-console/future-openshift/api-explorer/img/full.png
  web-console/future-openshift/api-explorer/img/pod-schema.png
  web-console/future-openshift/api-explorer/img/pod.png
Labels: size/M

#214 OB/OBC Lifecycle Management Design
  README.md
  web-console/Storage/OB-OB-Lifecycle-Management/OB-OBC-Lifecycle.md
  web-console/Storage/OB-OB-Lifecycle-Management/img/OB-create.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OB-list.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OB-overview.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OBC-attach-pod-01.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OBC-attach-pod.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OBC-create.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OBC-delete-obc.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OBC-list.png
  web-console/Storage/OB-OB-Lifecycle-Management/img/OBC-overview.png
Labels: size/L

#220 Add Cluster Overview Dashboard documentation
  web-console/knikubevirt/cluster-dashboard/cluster-dashboard.md
  web-console/knikubevirt/cluster-dashboard/cluster-dashboard.sketch
  web-console/knikubevirt/cluster-dashboard/img/0-1-details.png
  web-console/knikubevirt/cluster-dashboard/img/0-2-health.png
  web-console/knikubevirt/cluster-dashboard/img/0-3-events.png
  web-console/knikubevirt/cluster-dashboard/img/0-4-inventory.png
  web-console/knikubevirt/cluster-dashboard/img/0-5-capacity.png
  web-console/knikubevirt/cluster-dashboard/img/0-6-utilization.png
  web-console/knikubevirt/cluster-dashboard/img/0-7-consumption.png
  web-console/knikubevirt/cluster-dashboard/img/1-0-cluster-healthy.png
  web-console/knikubevirt/cluster-dashboard/img/1-1-cluster-unhealthy.png
  web-console/knikubevirt/knikubevirt.md
Labels: size/M

#236 Updated Advanced Section
  web-console/developer/advanced/advanced.md
  web-console/developer/advanced/img/image1.png
  web-console/developer/advanced/img/image2.png
  web-console/developer/advanced/img/image3.png
  web-console/developer/advanced/img/image4.png
Labels: size/S
