Repository openshift/openshift-origin-design, pull requests merged in 2019-08, with the labels that each got.

#230 Adding Import YAML documentation
  README.md
  web-console/future-openshift/import-yaml/img/editor.png
  web-console/future-openshift/import-yaml/img/icon.png
  web-console/future-openshift/import-yaml/import-yaml.md
Labels: size/S

#233 Create VM wizard - Networking step
  web-console/knikubevirt/Create-vm/2.networking/create-vm-networking.md
  web-console/knikubevirt/Create-vm/2.networking/img/3-00.png
  web-console/knikubevirt/Create-vm/2.networking/img/3-01.png
  web-console/knikubevirt/Create-vm/2.networking/img/3-02.png
  web-console/knikubevirt/Create-vm/2.networking/img/3-10.png
  web-console/knikubevirt/Create-vm/2.networking/img/3-20.png
  web-console/knikubevirt/knikubevirt.md
Labels: size/S

#238 add Pipelines design documentation
  web-console/developer/pipelines/img/PL-Details-Overview-Actions.png
  web-console/developer/pipelines/img/PL-Details-Overview.png
  web-console/developer/pipelines/img/PL-Details-PLR-Actions.png
  web-console/developer/pipelines/img/PL-Details-PLR-DeleteConfirmation.png
  web-console/developer/pipelines/img/PL-Details-PLR.png
  web-console/developer/pipelines/img/PL-Details-Parameters.png
  web-console/developer/pipelines/img/PL-Details-Resources-AddResource01.png
  web-console/developer/pipelines/img/PL-Details-Resources-AddResource02.png
  web-console/developer/pipelines/img/PL-Details-Resources-AddResource04.png
  web-console/developer/pipelines/img/PL-Details-Resources-RemoveResource.png
  web-console/developer/pipelines/img/PL-Details-Resources-RemoveResource01.png
  web-console/developer/pipelines/img/PL-Details-Resources-RemoveResource02.png
  web-console/developer/pipelines/img/PL-Details-Resources.png
  web-console/developer/pipelines/img/PL-Details-StartAction.png
  web-console/developer/pipelines/img/PL-Details-YAML.png
  web-console/developer/pipelines/img/PL-ListView-AllProjects.png
  web-console/developer/pipelines/img/PL-ListView-DeleteConfirmation.png
  web-console/developer/pipelines/img/PL-ListView-Kebab.png
  web-console/developer/pipelines/img/PL-ListView.png
  web-console/developer/pipelines/img/PLR-Details-Actions.png
  web-console/developer/pipelines/img/PLR-Details-Logs.png
  web-console/developer/pipelines/img/PLR-Details-Overview.png
  web-console/developer/pipelines/img/PLRVisualization.png
  web-console/developer/pipelines/img/PLVisualization.png
  web-console/developer/pipelines/pipelines.md
Labels: size/L

#209 PF4 updates for Migrate VM
  web-console/knikubevirt/migrate-vm/img/1-0-list.png
  web-console/knikubevirt/migrate-vm/img/1-1-modal-info.png
  web-console/knikubevirt/migrate-vm/img/1-2-modal-migrate.png
  web-console/knikubevirt/migrate-vm/img/1-3-list-notification-started.png
  web-console/knikubevirt/migrate-vm/img/1-4-list-notification-completed.png
  web-console/knikubevirt/migrate-vm/img/error.png
  web-console/knikubevirt/migrate-vm/img/popover.png
  web-console/knikubevirt/migrate-vm/migrate-vm.md
Labels: size/S

#241 Create Virtual Machine - Review Step
  web-console/knikubevirt/Create-vm/step-5-review/img/alert-toast-notification.png
  web-console/knikubevirt/Create-vm/step-5-review/img/check-settings.png
  web-console/knikubevirt/Create-vm/step-5-review/img/error-popover.png
  web-console/knikubevirt/Create-vm/step-5-review/img/fixed-and-creating.png
  web-console/knikubevirt/Create-vm/step-5-review/img/review-and-create-action.png
  web-console/knikubevirt/Create-vm/step-5-review/img/vm-starting.png
  web-console/knikubevirt/Create-vm/step-5-review/wizard-review.md
  web-console/knikubevirt/knikubevirt.md
  web-console/knikubevirt/wizard-import/wizard-import.md
Labels: size/M

#239 Create Virtual Machine - General Step
  web-console/knikubevirt/Create-vm/img/Step-1-basic-Flavour.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-ISO-2.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-ISO.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-Image-1.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-Image-2.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-Operating-system-1.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-Operating-system-2.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-Operating-system-3.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-PXE-1.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-appliance-1.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-appliance-2.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-attach-disk-dropdown.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-attach-disk-selected.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-attach-disk.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-container.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-namespace.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-no-template-chosen.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-template-2.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-template-3 Copy.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-template-3.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-template-4.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-template.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-url.png
  web-console/knikubevirt/Create-vm/img/Step-1-basic-workload-profile.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-Flavour.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-ISO-2.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-ISO.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-Image-1.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-Image-2.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-Operating-system-1.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-Operating-system-2.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-Operating-system-3.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-PXE-1.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-appliance-1.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-appliance-2.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-attach-disk-dropdown.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-attach-disk-selected.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-attach-disk.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-container.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-namespace.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-no-template-chosen.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-template-2.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-template-3 Copy.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-template-3.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-template-4.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-template.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-url.png
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-workload-profile.png
  web-console/knikubevirt/Create-vm/step-1-genaral/wizard-general.md
  web-console/knikubevirt/knikubevirt.md
Labels: size/XS

#235 Create VM wizard storage step
  web-console/knikubevirt/Create-vm/step-3-storage/img/Add-disk-default.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Add-disk-modal-ISO-selected.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Add-disk-modal-details-required.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Add-disk-modal.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Attach-disk-selected-add-disk-modal-details-required.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Attach-disk-selected-add-disk-modal-details-required2.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Attach-disk-selected-add-disk-modal.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Container-selected-add-disk-modal-details-required.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Container-selected-add-disk-modal.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Create-new-ISO.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Edit-disk-modal.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Edit-disk.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Empty-state-after-deleting-all-items.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Remove-disk-warning-alert.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Remove-disk.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/URL-selected-add-disk-modal-details-required.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/URL-selected-add-disk-modal.png
  web-console/knikubevirt/Create-vm/step-3-storage/img/Upload-new-ISO.png
  web-console/knikubevirt/Create-vm/step-3-storage/wizard-storage.md
  web-console/knikubevirt/knikubevirt.md
Labels: size/M

#254 broken link
  .vscode/settings.json
  web-console/knikubevirt/Create-vm/step-2-networking/create-vm-networking.md
  web-console/knikubevirt/Create-vm/step-2-networking/img/3-00.png
  web-console/knikubevirt/Create-vm/step-2-networking/img/3-01.png
  web-console/knikubevirt/Create-vm/step-2-networking/img/3-02.png
  web-console/knikubevirt/Create-vm/step-2-networking/img/3-10.png
  web-console/knikubevirt/Create-vm/step-2-networking/img/3-20.png
  web-console/knikubevirt/knikubevirt.md
Labels: size/XS

#256 fix
  web-console/knikubevirt/knikubevirt.md
Labels: size/XS

#240 Create A Virtual Machine - Import VM
  web-console/knikubevirt/Create-vm/wizard-import/img/connecting-to-new-instance.png
  web-console/knikubevirt/Create-vm/wizard-import/img/credentials-checked.png
  web-console/knikubevirt/Create-vm/wizard-import/img/credentials-updated-username-psw-fields-collapse.png
  web-console/knikubevirt/Create-vm/wizard-import/img/default.png
  web-console/knikubevirt/Create-vm/wizard-import/img/empty-state.png
  web-console/knikubevirt/Create-vm/wizard-import/img/new-fields-required.png
  web-console/knikubevirt/Create-vm/wizard-import/img/save-credentials.png
  web-console/knikubevirt/Create-vm/wizard-import/img/selecting-provider.png
  web-console/knikubevirt/Create-vm/wizard-import/img/selecting-vcenter-instance.png
  web-console/knikubevirt/Create-vm/wizard-import/img/selecting-virtual-machine.png
  web-console/knikubevirt/Create-vm/wizard-import/img/user-unchecks.png
  web-console/knikubevirt/Create-vm/wizard-import/img/vcenter-connection-error.png
  web-console/knikubevirt/Create-vm/wizard-import/img/vcenter-connection-incorrect-credentials.png
  web-console/knikubevirt/Create-vm/wizard-import/img/vm-available-from-new-instance.png
  web-console/knikubevirt/Create-vm/wizard-import/wizard-import.md
Labels: size/M

#211 OCS Installation UI flow
  README.md
  web-console/Storage/OCS/OCS _Installation_Workflow.md
  web-console/Storage/OCS/img/Create_new_OCS_00.png
  web-console/Storage/OCS/img/Create_new_OCS_01.png
  web-console/Storage/OCS/img/Create_new_OCS_01_Additional_nodes.png
  web-console/Storage/OCS/img/Create_new_OCS_01_error.png
  web-console/Storage/OCS/img/Installed_MCG_Tab_healthy.png
  web-console/Storage/OCS/img/Installed_OCS_MCG_Overview.png
  web-console/Storage/OCS/img/Installed_OCS_OCS_Overview.png
  web-console/Storage/OCS/img/Installed_OCS_OCS_Tab_deploy.png
  web-console/Storage/OCS/img/Installed_OCS_OCS_Tab_healthy.png
  web-console/Storage/OCS/img/Installed_OCS_Overview.png
  web-console/Storage/OCS/img/Installed_operators_list.png
  web-console/Storage/OCS/img/MCG_resource_page_details.png
  web-console/Storage/OCS/img/OCS-Install-step1.png
  web-console/Storage/OCS/img/OCS-Install-step2.png
  web-console/Storage/OCS/img/OCS-View.png
  web-console/Storage/OCS/img/OCS-operator-view.png
  web-console/Storage/OCS/img/OCS_Subscription_page.png
  web-console/Storage/OCS/img/Operator_Catalog_list.png
  web-console/Storage/OCS/img/info.png
Labels: size/M

#252 update with latest mocks
  web-console/developer/pipelines/img/PL-Details-Overview-Actions.png
  web-console/developer/pipelines/img/PL-Details-Overview.png
  web-console/developer/pipelines/img/PL-Details-PLR-Actions.png
  web-console/developer/pipelines/img/PL-Details-PLR-DeleteConfirmation.png
  web-console/developer/pipelines/img/PL-Details-PLR.png
  web-console/developer/pipelines/img/PL-Details-StartAction.png
  web-console/developer/pipelines/img/PL-ListView-Kebab.png
  web-console/developer/pipelines/img/PL-ListView.png
  web-console/developer/pipelines/img/PLR-Details-Actions.png
  web-console/developer/pipelines/img/PLR-Details-Logs.png
  web-console/developer/pipelines/img/PLR-Details-Overview.png
  web-console/developer/pipelines/img/PLRVisualization.png
  web-console/developer/pipelines/img/PLVisualization.png
Labels: size/XS

#237 Updating Builds tab of Dev Console
  web-console/developer/builds/builds.md
  web-console/developer/builds/img/image1.png
  web-console/developer/builds/img/image2.png
  web-console/developer/builds/img/image3.png
  web-console/developer/builds/img/image4.png
Labels: size/S

#261 Updated README.md
  README.md
Labels: size/XS

#266 update readme.md
  README.md
Labels: size/XS

#263 add example of when a windows OS is selected
  web-console/knikubevirt/Create-vm/step-1-genaral/img/Step-1-basic-Operating-system-Windows-os-selected.png
  web-console/knikubevirt/Create-vm/step-1-genaral/wizard-general.md
Labels: size/S

#268 removes section titles
  web-console/knikubevirt/Create-vm/step-1-genaral/wizard-general.md
Labels: size/XS
