Repository openshift/openshift-origin-design, pull requests merged in 2019-02, with the labels that each got.

#146 New Copy login command feature added
  README.md
  web-console/4.0-designs/user/img/copy-login-command-1.png
  web-console/4.0-designs/user/img/copy-login-command-3.png
  web-console/4.0-designs/user/img/copy-login-command.png
  web-console/4.0-designs/user/user.md
Labels: size/S

#145 Adding OAuth and IDP documentation
  README.md
  web-console/futures/oauth/img/future.png
  web-console/futures/oauth/img/list.png
  web-console/futures/oauth/img/v3-1.png
  web-console/futures/oauth/img/v3-2.png
  web-console/futures/oauth/img/v3-3.png
  web-console/futures/oauth/img/v3-4.png
  web-console/futures/oauth/img/v3-5.png
  web-console/futures/oauth/img/v3-6.png
  web-console/futures/oauth/oauth.md
Labels: size/M

#150 Updating quotas on Project Status
  web-console/4.0-designs/dashboard/dashboard.md
  web-console/4.0-designs/dashboard/img/quota-even.png
  web-console/4.0-designs/dashboard/img/quota-odd.png
  web-console/4.0-designs/dashboard/img/quotas.png
Labels: size/XS

#149 Adding chargeback guidelines
  web-console/futures/chargeback/chargeback.md
  web-console/futures/chargeback/img/create-report.png
  web-console/futures/chargeback/img/pending-report.png
  web-console/futures/chargeback/img/report-details-instance-type.png
  web-console/futures/chargeback/img/report-details-sort.png
  web-console/futures/chargeback/img/report-details.png
  web-console/futures/chargeback/img/reports-list.png
Labels: size/S

#148 Adding documentation for taints and tolerations
  README.md
  web-console/4.0-designs/taints-tolerations/img/node-details.png
  web-console/4.0-designs/taints-tolerations/img/node-taints.png
  web-console/4.0-designs/taints-tolerations/img/nodes-list.png
  web-console/4.0-designs/taints-tolerations/img/pod-details.png
  web-console/4.0-designs/taints-tolerations/img/pod-tolerations.png
  web-console/4.0-designs/taints-tolerations/taints-tolerations.md
Labels: size/S
