Repository openshift/openshift-origin-design, pull requests merged in 2020-03, with the labels that each got.

#349 Add first research article
  research/alert_descriptions/img/1_KubePodNotReady.png
  research/alert_descriptions/img/all.png
  research/alert_descriptions/img/all_exp.png
  research/alert_descriptions/img/click_area_all.png
  research/alert_descriptions/img/conf_viol2.png
  research/alert_descriptions/img/exp_and_use.png
  research/alert_descriptions/img/vers2.png
  research/alert_descriptions/img/view_details.png
  research/alert_descriptions/index.md
  research/index.md
Labels: size/L

#351 exposing config maps secrets services in vm ui
  designs/virtualization/4.x/exposing config maps  secrets  service account in VM UI/exposing config maps.md
  designs/virtualization/4.x/exposing config maps  secrets  service account in VM UI/img/expose-secret1.png
  designs/virtualization/4.x/exposing config maps  secrets  service account in VM UI/img/expose-secret10.png
  designs/virtualization/4.x/exposing config maps  secrets  service account in VM UI/img/expose-secret11.png
  designs/virtualization/4.x/exposing config maps  secrets  service account in VM UI/img/expose-secret2.png
  designs/virtualization/4.x/exposing config maps  secrets  service account in VM UI/img/expose-secret3.png
  designs/virtualization/4.x/exposing config maps  secrets  service account in VM UI/img/expose-secret4.png
  designs/virtualization/4.x/exposing config maps  secrets  service account in VM UI/img/expose-secret5.png
  designs/virtualization/4.x/exposing config maps  secrets  service account in VM UI/img/expose-secret6.png
  designs/virtualization/4.x/exposing config maps  secrets  service account in VM UI/img/expose-secret7.png
  designs/virtualization/4.x/exposing config maps  secrets  service account in VM UI/img/expose-secret8.png
  designs/virtualization/4.x/exposing config maps  secrets  service account in VM UI/img/expose-secret9.png
Labels: size/M

#340 Site: Fix version page ordering and embiggen search icon
  _layouts/default.html
  _sass/overrides.scss
Labels: size/M

#357 adding 4.4 designs
  designs/developer/add-44/From-Catalog/Add-from-catalog.md
  designs/developer/add-44/From-Catalog/Catalog-HelmChart.md
  designs/developer/add-44/From-Catalog/Catalog-OperatorBackedService.md
  designs/developer/add-44/From-Catalog/img/HelmReleases-Collapsed-Topology-SidePanel.png
  designs/developer/add-44/From-Catalog/img/HelmReleases-Collapsed-Topology.png
  designs/developer/add-44/From-Catalog/img/HelmReleases-Topology.png
  designs/developer/add-44/From-Catalog/img/InstallHelmChart.png
  designs/developer/index.md
  designs/developer/monitoring-44/img/Monitoring-Dashboard-PerWorkload.png
  designs/developer/monitoring-44/img/Monitoring-Dashboard.png
  designs/developer/monitoring-44/img/Monitoring-Metrics-CustomerQuery.png
  designs/developer/monitoring-44/img/Monitoring-Metrics-MemoryUsage.png
  designs/developer/monitoring-44/img/Monitoring-Metrics-SelectQuery.png
  designs/developer/monitoring-44/img/Monitoring-Metrics.png
  designs/developer/monitoring-44/img/Topology-SidePanel-MonitoringTab.png
  designs/developer/monitoring-44/index.md
Labels: size/L

#358 Update PLR-Details-Overview.png
  designs/developer/operator-pipeline-42/img/PLR-Details-Actions.png
  designs/developer/operator-pipeline-42/img/PLR-Details-Overview.png
Labels: size/XS

#359 Update images with better quality
  designs/developer/operator-pipeline-42/img/PLR-Details-Actions.png
  designs/developer/operator-pipeline-42/img/PLR-Details-Overview.png
Labels: size/XS

#360 operator backed services
  designs/developer/add-44/From-Catalog/Catalog-OperatorBackedService.md
  designs/developer/add-44/From-Catalog/img/Topology-DisplayMenu.png
  designs/developer/add-44/From-Catalog/img/Topology-OperatorGroupingCollapsed.png
  designs/developer/add-44/From-Catalog/img/Topology-OperatorGroupingExpanded.png
  designs/developer/add-44/index.md
  designs/developer/index.md
  designs/developer/operator-pipeline-44/index.md
  designs/developer/operator-pipeline-44/pipeline-builder.md
Labels: size/M

#355 Documentation for topology 4.4 features added
  designs/developer/index.md
  designs/developer/topology-44/img/collapsed_group.png
  designs/developer/topology-44/img/displaydropdown_access.png
  designs/developer/topology-44/img/displaydropdown_applicationgrouping.png
  designs/developer/topology-44/img/displaydropdown_applicationscollapsed.png
  designs/developer/topology-44/img/displaydropdown_podcount.png
  designs/developer/topology-44/img/displaydropdown_podcounton.png
  designs/developer/topology-44/img/displaydropdown_podcounttrigger.png
  designs/developer/topology-44/img/find_resulthighlighted.png
  designs/developer/topology-44/img/find_starttyping.png
  designs/developer/topology-44/img/find_tooltip.png
  designs/developer/topology-44/img/incontextadd_options.png
  designs/developer/topology-44/img/incontextadd_rightclick.png
  designs/developer/topology-44/img/incontextadd_trigger.png
  designs/developer/topology-44/index.md
  designs/developer/topology-44/topology-filter.md
  designs/developer/topology-44/topology-find.md
  designs/developer/topology-44/topology-grouping.md
  designs/developer/topology-44/topology-in-context-add.md
Labels: size/L

#347 Site: Nav tweaks, optional smarts, and personal website previews
  _config.yml
  _includes/head.html
  _includes/nav.html
  _includes/toc.html
  _layouts/default.html
  _sass/overrides.scss
  designs/administrator/4.0/edit-yaml/index.md
  designs/administrator/4.0/navigation/index.md
  designs/administrator/4.0/status/index.md
  designs/administrator/future-openshift/code-editor-updates/index.md
  designs/administrator/index.md
  designs/concepts/index.md
  designs/developer/index.md
  designs/developer/operator-pipeline-42/rbac-pipelines.md
Labels: size/L

#343 Add alertmanager configuration updates for 4.5
  designs/administrator/4.5/alertmanager-config/img/alertmanager-all-configured.png
  designs/administrator/4.5/alertmanager-config/img/alertmanager-editing-critical.png
  designs/administrator/4.5/alertmanager-config/img/alertmanager-editing-default.png
  designs/administrator/4.5/alertmanager-config/img/alertmanager-editing-watchdog.png
  designs/administrator/4.5/alertmanager-config/img/alertmanager-first-time.png
  designs/administrator/4.5/alertmanager-config/img/alertmanager-incomplete-critical.png
  designs/administrator/4.5/alertmanager-config/index.md
Labels: size/S

#363 Add 'Infrastructure Features' and 'Paid Subscription Required' filters to OperatorHub
  designs/administrator/olm/operatorhub-features-subscription-filters/img/1-1-OH-functionality.png
  designs/administrator/olm/operatorhub-features-subscription-filters/img/1-2-OHdeets-funcationality.png
  designs/administrator/olm/operatorhub-features-subscription-filters/index.md
Labels: size/S

#354 Adding custom operator delete message design
  designs/administrator/olm/custom-operator-delete-message/img/1-1-header.png
  designs/administrator/olm/custom-operator-delete-message/index.md
Labels: size/S
