Repository openshift/openshift-origin-design, pull requests merged in 2020-01, with the labels that each got.

#313 Changes to the Add page with links to different flows.
  dev-perspective/add/Container-Image/Deploy-Image.md
  dev-perspective/add/From-Catalog/Create-Source-to-image-application.md
  dev-perspective/add/From-Dockerfile/Import-from-Dockerfile.md
  dev-perspective/add/From-Git/Import-from-git.md
  dev-perspective/add/add.md
  dev-perspective/add/sections/Resources/Resources.md
Labels: size/M

#299 Topology Documentation
  dev-perspective/topology/img/Edit_app_grouping_new.png
  dev-perspective/topology/img/Edit_application_grouping_dialogue.png
  dev-perspective/topology/img/Select_app_group.png
  dev-perspective/topology/img/Topology_View.png
  dev-perspective/topology/img/application_change_grouping.png
  dev-perspective/topology/img/application_delete.png
  dev-perspective/topology/img/application_delete_menu.png
  dev-perspective/topology/img/application_deleted.png
  dev-perspective/topology/img/application_edit_grouping.png
  dev-perspective/topology/img/application_editgrouping_menu.png
  dev-perspective/topology/img/application_group.png
  dev-perspective/topology/img/application_hover.png
  dev-perspective/topology/img/application_select.png
  dev-perspective/topology/img/application_selector.png
  dev-perspective/topology/img/build_status.png
  dev-perspective/topology/img/che_icon.png
  dev-perspective/topology/img/connection_created.png
  dev-perspective/topology/img/connection_delete.png
  dev-perspective/topology/img/connector_arrow_hover.png
  dev-perspective/topology/img/connector_clickndrag.png
  dev-perspective/topology/img/connector_created.png
  dev-perspective/topology/img/connector_delete.png
  dev-perspective/topology/img/connector_delete_hover.png
  dev-perspective/topology/img/connector_delete_tooltip.png
  dev-perspective/topology/img/connector_dragconnected.png
  dev-perspective/topology/img/connector_dragndrop.png
  dev-perspective/topology/img/connector_dragnmove.png
  dev-perspective/topology/img/connector_hover.png
  dev-perspective/topology/img/connector_hover_dangler.png
  dev-perspective/topology/img/connector_move_tooltip.png
  dev-perspective/topology/img/connector_no_connection.png
  dev-perspective/topology/img/connector_selected_state.png
  dev-perspective/topology/img/connector_unselected_state.png
  dev-perspective/topology/img/delete_application_group.png
  dev-perspective/topology/img/delete_component.png
  dev-perspective/topology/img/git_alt.png
  dev-perspective/topology/img/github_icon.png
  dev-perspective/topology/img/image39.png
  dev-perspective/topology/img/image68.png
  dev-perspective/topology/img/image69.png
  dev-perspective/topology/img/moved_node.png
  dev-perspective/topology/img/no1.png
  dev-perspective/topology/img/no_project_exists.png
  dev-perspective/topology/img/no_workload_exists.png
  dev-perspective/topology/img/node_delete_confirmation.png
  dev-perspective/topology/img/node_design.png
  dev-perspective/topology/img/node_drag_newapp.png
  dev-perspective/topology/img/node_label.png
  dev-perspective/topology/img/node_move_dialogue.png
  dev-perspective/topology/img/node_select.png
  dev-perspective/topology/img/node_sidepanel.png
  dev-perspective/topology/img/pipeline_status.png
  dev-perspective/topology/img/pod_status.png
  dev-perspective/topology/img/select_connector.png
  dev-perspective/topology/topology.md
Labels: size/L

#312 Add Red Hat Marketplace Support
  admin-perspective/admin-perspective.md
  admin-perspective/olm/openmarketplace-support/img/1-1-linktomarketplace.png
  admin-perspective/olm/openmarketplace-support/img/1-2-purchasemarketplace.png
  admin-perspective/olm/openmarketplace-support/img/1-3-purchasemarketplace-installed.png
  admin-perspective/olm/openmarketplace-support/openmarketplace-support.md
Labels: size/S

#307 Add Operator-defined Installation Namespace
  admin-perspective/admin-perspective.md
  admin-perspective/olm/install-forcenamespace/img/1-1-noDefinedNS-all.png
  admin-perspective/olm/install-forcenamespace/img/1-2-noDefinedNS-single.png
  admin-perspective/olm/install-forcenamespace/img/1-3-noDefinedNS-single.png
  admin-perspective/olm/install-forcenamespace/img/1-4-noDefinedNS-single.png
  admin-perspective/olm/install-forcenamespace/img/1-5-noDefinedNS-single.png
  admin-perspective/olm/install-forcenamespace/img/1-6-noDefinedNS-single.png
  admin-perspective/olm/install-forcenamespace/img/2-1-definedNS-all.png
  admin-perspective/olm/install-forcenamespace/img/2-2-definedNS-single.png
  admin-perspective/olm/install-forcenamespace/img/2-3-definedNS-single.png
  admin-perspective/olm/install-forcenamespace/img/2-4-definedNS-single.png
  admin-perspective/olm/install-forcenamespace/img/2-5-definedNS-single.png
  admin-perspective/olm/install-forcenamespace/img/3-1-definedNSCreate-all.png
  admin-perspective/olm/install-forcenamespace/img/3-2-definedNSCreate-single.png
  admin-perspective/olm/install-forcenamespace/img/4-1-definedNSMonitor-all.png
  admin-perspective/olm/install-forcenamespace/img/4-2-definedNSMonitor-single.png
  admin-perspective/olm/install-forcenamespace/img/4-3-definedNSMonitor-single.png
  admin-perspective/olm/install-forcenamespace/img/4-4-definedNSMonitor-single.png
  admin-perspective/olm/install-forcenamespace/img/4-5-definedNSMonitor-single.png
  admin-perspective/olm/install-forcenamespace/img/5-1-definedNSCreateMonitor-single.png
  admin-perspective/olm/install-forcenamespace/img/9-1-error-desiredGroup.png
  admin-perspective/olm/install-forcenamespace/img/9-2-error-fixedGroup.png
  admin-perspective/olm/install-forcenamespace/install-forcenamespace.md
Labels: size/M

#314 Operand Creation Form/YAML Switching
  admin-perspective/admin-perspective.md
  admin-perspective/olm/operand-form-yaml-switching/img/1-1-adminOperand-yaml.png
  admin-perspective/olm/operand-form-yaml-switching/img/1-2-adminOperand-yaml-sidebar.png
  admin-perspective/olm/operand-form-yaml-switching/img/1-3-adminOperand-form.png
  admin-perspective/olm/operand-form-yaml-switching/operand-form-yaml-switching.md
Labels: size/S

#310 Surfacing VMIs in the UI
  web-console/knikubevirt/VMIs/VMIs.md
  web-console/knikubevirt/VMIs/img/Op1Actions.png
  web-console/knikubevirt/VMIs/img/Op1WarningPopupDelete.png
  web-console/knikubevirt/VMIs/img/Op1_VMI_DetailsViewPlusHint.png
  web-console/knikubevirt/VMIs/img/Op2_Hint.png
  web-console/knikubevirt/VMIs/img/VM_DetailsPageW_LinkToVMI.png
  web-console/knikubevirt/VMIs/img/VMsListW_VMIsOp2.png
  web-console/knikubevirt/VMIs/img/WarningPopupDelete_VMIHasAnOwner.png
Labels: size/M

#306 Add notification drawer MVP designs
  admin-perspective/4.4/notification-drawer/img/notifications-closed.png
  admin-perspective/4.4/notification-drawer/img/notifications-empty.png
  admin-perspective/4.4/notification-drawer/img/notifications-error.png
  admin-perspective/4.4/notification-drawer/img/notifications-no-critical-expanded.png
  admin-perspective/4.4/notification-drawer/img/notifications-no-critical.png
  admin-perspective/4.4/notification-drawer/img/notifications-only-messages.png
  admin-perspective/4.4/notification-drawer/img/notifications-open.png
  admin-perspective/4.4/notification-drawer/img/notifications-receivers.png
  admin-perspective/4.4/notification-drawer/img/notifications-updates.png
  admin-perspective/4.4/notification-drawer/notification-drawer.md
  admin-perspective/admin-perspective.md
Labels: size/M

#315 Fix new site assets not loading
  _config.yml
Labels: size/XS

#316 Update PF component table
  conventions/documentation/componentstatus.md
Labels: size/XS

#317 Users and Groups pages in User Management section for 4.3
  designs/administrator/4.3/users-groups/img/image1-67.png
  designs/administrator/4.3/users-groups/img/image2-56.png
  designs/administrator/4.3/users-groups/img/image3-49.png
  designs/administrator/4.3/users-groups/img/image4-40.png
  designs/administrator/4.3/users-groups/img/image5-38.png
  designs/administrator/4.3/users-groups/img/image6-35.png
  designs/administrator/4.3/users-groups/img/image7-29.png
  designs/administrator/4.3/users-groups/index.md
Labels: size/M
