Repository openshift/openshift-origin-design, pull requests merged in 2020-02, with the labels that each got.

#325 Topology - Side panel contents for Serverless resources
  designs/developer/operator-serverless-44/img/sidepanel-KSVC-autoscaled.png
  designs/developer/operator-serverless-44/img/sidepanel-KSVC.png
  designs/developer/operator-serverless-44/img/sidepanel-REV-autoscaled.png
  designs/developer/operator-serverless-44/img/sidepanel-REV.png
  designs/developer/operator-serverless-44/index.md
Labels: size/S

#320 Quay Image Vulnerabilities list and details & cluster dashboard vulnerability status improvements
  designs/administrator/4.4/quay-imagemanifestvuln-list/img/1imvlist.png
  designs/administrator/4.4/quay-imagemanifestvuln-list/img/2imvoverview.png
  designs/administrator/4.4/quay-imagemanifestvuln-list/img/3imvpods.png
  designs/administrator/4.4/quay-imagemanifestvuln-list/img/4podlistactions.png
  designs/administrator/4.4/quay-imagemanifestvuln-list/img/5filteredimvlist.png
  designs/administrator/4.4/quay-imagemanifestvuln-list/img/6dash.png
  designs/administrator/4.4/quay-imagemanifestvuln-list/index.md
Labels: size/M

#319 Quay Security Integration for 4.3
  designs/administrator/4.3/quay-image-security/img/image1-73.png
  designs/administrator/4.3/quay-image-security/img/image3-55.png
  designs/administrator/4.3/quay-image-security/index.md
Labels: size/S

#323 Adding list improvements documentation
  designs/administrator/4.4/list-updates/img/nodes1.png
  designs/administrator/4.4/list-updates/img/nodes2.png
  designs/administrator/4.4/list-updates/img/pods.png
  designs/administrator/4.4/list-updates/img/projects.png
  designs/administrator/4.4/list-updates/index.md
Labels: size/S

#322 Update Masthead icons
  designs/administrator/4.4/notification-drawer/img/notifications-closed.png
  designs/administrator/4.4/notification-drawer/img/notifications-error.png
  designs/administrator/4.4/notification-drawer/img/notifications-icon.png
  designs/administrator/4.4/notification-drawer/img/notifications-no-critical-expanded.png
  designs/administrator/4.4/notification-drawer/img/notifications-no-critical.png
  designs/administrator/4.4/notification-drawer/img/notifications-only-messages.png
  designs/administrator/4.4/notification-drawer/img/notifications-open.png
  designs/administrator/4.4/notification-drawer/img/notifications-receivers.png
  designs/administrator/4.4/notification-drawer/img/notifications-updates.png
  designs/administrator/4.4/notification-drawer/index.md
Labels: size/XS

#321 Add metrics dashboard designs
  designs/administrator/4.4/metrics-dashboards/img/dashboard-area-chart.png
  designs/administrator/4.4/metrics-dashboards/img/dashboard-dropdown.png
  designs/administrator/4.4/metrics-dashboards/img/dashboard-graph-area.png
  designs/administrator/4.4/metrics-dashboards/img/dashboard-graph-bar.png
  designs/administrator/4.4/metrics-dashboards/img/dashboard-graph-line.png
  designs/administrator/4.4/metrics-dashboards/img/dashboard-singlestat.png
  designs/administrator/4.4/metrics-dashboards/img/dashboard-table.png
  designs/administrator/4.4/metrics-dashboards/img/dashboard-toolbar-tabs.png
  designs/administrator/4.4/metrics-dashboards/img/dashboard-toolbar.png
  designs/administrator/4.4/metrics-dashboards/img/dashboard-whole.png
  designs/administrator/4.4/metrics-dashboards/index.md
Labels: size/M

#335 Reformatting dev again
  designs/developer/add-43/img/Add-AltA.png
  designs/developer/add-43/img/dev-add.png
  designs/developer/add-43/img/import-yaml.png
  designs/developer/add-43/index.md
  designs/developer/add-43/sections/pipelines/img/+Add_Flow_Add_Pipe.png
  designs/developer/add-43/sections/pipelines/img/+Add_Flow_Pipelines_Docker_No_Temp.png
  designs/developer/add-43/sections/pipelines/img/+Add_Flow_Pipelines_ImportFromGit.png
  designs/developer/add-43/sections/pipelines/img/+Add_Flow_Pipelines_ImportFromGit_No_Img.png
  designs/developer/add-43/sections/pipelines/img/+Add_Flow_Pipelines_ImportFromGit_No_Temp.png
  designs/developer/add-43/sections/pipelines/img/+Add_Flow_Show_Pipe_Viz.png
  designs/developer/add-43/sections/pipelines/img/+Add_Flow_Showing_Pipe_Viz.png
  designs/developer/add-43/sections/pipelines/pipelines.md
  designs/developer/add-43/sections/resources/resources.md
  designs/developer/add-44/img/Add-AltA.png
  designs/developer/add-44/img/dev-add.png
  designs/developer/add-44/img/import-yaml.png
  designs/developer/add-44/index.md
  designs/developer/add/Container-Image/Deploy-Image.md
  designs/developer/add/From-Catalog/Add-from-catalog.md
  designs/developer/add/From-Catalog/Create-Source-to-image-application.md
  designs/developer/add/From-Dockerfile/Import-from-Dockerfile.md
  designs/developer/add/From-Git/Import-from-git.md
  designs/developer/add/index.md
  designs/developer/add/sections/Adv-Build-Config.md
  designs/developer/add/sections/Adv-Deployment-Config.md
  designs/developer/add/sections/Adv-Labels.md
  designs/developer/add/sections/Adv-Resource-Limits.md
  designs/developer/add/sections/Adv-Routing.md
  designs/developer/add/sections/Adv-Scaling.md
  designs/developer/add/sections/General-Section.md
  designs/developer/index.md
Labels: size/XL

#338 Reformatting dev again
  designs/developer/add-43/index.md
  designs/developer/add-43/sections/pipelines/pipelines.md
  designs/developer/add-43/sections/resources/resources.md
  designs/developer/add-44/index.md
  designs/developer/add/Container-Image/Deploy-Image.md
  designs/developer/add/From-Catalog/Add-from-catalog.md
  designs/developer/add/From-Dockerfile/Import-from-Dockerfile.md
  designs/developer/add/From-Git/Import-from-git.md
  designs/developer/add/index.md
  designs/developer/index.md
  designs/developer/operator-pipeline-42/img/PL-Details-Overview-Actions.png
  designs/developer/operator-pipeline-42/img/PL-Details-Overview.png
  designs/developer/operator-pipeline-42/img/PL-Details-PLR-Actions.png
  designs/developer/operator-pipeline-42/img/PL-Details-PLR-DeleteConfirmation.png
  designs/developer/operator-pipeline-42/img/PL-Details-PLR.png
  designs/developer/operator-pipeline-42/img/PL-Details-Parameters.png
  designs/developer/operator-pipeline-42/img/PL-Details-Resources-AddResource01.png
  designs/developer/operator-pipeline-42/img/PL-Details-Resources-AddResource02.png
  designs/developer/operator-pipeline-42/img/PL-Details-Resources-AddResource04.png
  designs/developer/operator-pipeline-42/img/PL-Details-Resources-RemoveResource.png
  designs/developer/operator-pipeline-42/img/PL-Details-Resources-RemoveResource01.png
  designs/developer/operator-pipeline-42/img/PL-Details-Resources-RemoveResource02.png
  designs/developer/operator-pipeline-42/img/PL-Details-Resources.png
  designs/developer/operator-pipeline-42/img/PL-Details-StartAction.png
  designs/developer/operator-pipeline-42/img/PL-Details-YAML.png
  designs/developer/operator-pipeline-42/img/PL-ListView-AllProjects.png
  designs/developer/operator-pipeline-42/img/PL-ListView-DeleteConfirmation.png
  designs/developer/operator-pipeline-42/img/PL-ListView-Kebab.png
  designs/developer/operator-pipeline-42/img/PL-ListView.png
  designs/developer/operator-pipeline-42/img/PLR-Details-Actions.png
  designs/developer/operator-pipeline-42/img/PLR-Details-Logs.png
  designs/developer/operator-pipeline-42/img/PLR-Details-Overview.png
  designs/developer/operator-pipeline-42/img/PLRVisualization.png
  designs/developer/operator-pipeline-42/img/PLVisualization.png
  designs/developer/operator-pipeline-42/img/RBAC-PL-Details-Overview-Actions.png
  designs/developer/operator-pipeline-42/img/RBAC-PL-Details-PLR-Actions.png
  designs/developer/operator-pipeline-42/img/RBAC-PL-Details-Parameters.png
  designs/developer/operator-pipeline-42/img/RBAC-PL-Details-Resources.png
  designs/developer/operator-pipeline-42/img/RBAC-PL-Details-YAML.png
  designs/developer/operator-pipeline-42/img/RBAC-PL-ListView.png
  designs/developer/operator-pipeline-42/img/RBAC-PLR-Details-Actions.png
  designs/developer/operator-pipeline-42/index.md
  designs/developer/operator-pipeline-42/pipelines.md
  designs/developer/operator-pipeline-43/index.md
  designs/developer/operator-pipeline-44/index.md
  designs/developer/operator-serverless-42/index.md
  designs/developer/operator-serverless-43/index.md
  designs/developer/operator-serverless-44/index.md
Labels: size/L

#339 update formatting of dev index
  designs/developer/add-43/Container-Image/Deploy-Image.md
  designs/developer/add-43/index.md
  designs/developer/add-44/Container-Image/Deploy-Image.md
  designs/developer/add-44/index.md
  designs/developer/add/index.md
  designs/developer/index.md
Labels: size/L

#342 remove angle brackets
  designs/developer/index.md
Labels: size/XS

#334 Dedicated resources (previously CPU pinning)
  designs/virtualization/4.3/vm-details/dedicated-resources/dedicated-resources.md
  designs/virtualization/4.3/vm-details/dedicated-resources/img/in-page-0-1.jpg
  designs/virtualization/4.3/vm-details/dedicated-resources/img/in-page-0-2.jpg
  designs/virtualization/4.3/vm-details/dedicated-resources/img/modal-0-1.jpg
  designs/virtualization/4.3/vm-details/dedicated-resources/img/modal-0-2.jpg
Labels: size/S

#333 Variety of changes to the design conventions
  conventions/documentation/badges.md
  conventions/documentation/componentstatus.md
  conventions/documentation/create.md
  conventions/documentation/dashboards.md
  conventions/documentation/delete.md
  conventions/documentation/details.md
  conventions/documentation/edit.md
  conventions/documentation/empty states.md
  conventions/documentation/interactions.md
  conventions/documentation/lists.md
  conventions/documentation/metrics.md
  conventions/documentation/primarynavigation.md
  conventions/images/Alertmanager.png
  conventions/images/ConfigMap.png
  conventions/images/Could-not-connect.png
  conventions/images/Eventing.png
  conventions/images/Ingress.png
  conventions/images/Namespace.png
  conventions/images/Node.png
  conventions/images/Pipelines.png
  conventions/images/Pod.png
  conventions/images/Project.png
  conventions/images/RBAC-binding.png
  conventions/images/RBAC-role.png
  conventions/images/Secret.png
  conventions/images/Service.png
  conventions/images/Serving.png
  conventions/images/Small-empty-state-2.png
  conventions/images/Small-empty-state.png
  conventions/images/Updated contribute.jpg
  conventions/images/When-nothing-matches-a-filter.png
  conventions/images/When-there-are-no-workloads.png
  conventions/images/When-there-are-no-workloads2.png
  conventions/images/When-there-are-no-workloads3.png
  conventions/images/custom-resource.png
  conventions/images/pod-overlord.png
  conventions/images/pods-empty.png
  conventions/images/search-empty 9.34.45 AM.png
Labels: size/L
